package amberdb.sql.dao;


import java.util.List;

import org.skife.jdbi.v2.sqlobject.Bind;
import org.skife.jdbi.v2.sqlobject.CreateSqlObject;
import org.skife.jdbi.v2.sqlobject.GetGeneratedKeys;
import org.skife.jdbi.v2.sqlobject.SqlQuery;
import org.skife.jdbi.v2.sqlobject.SqlUpdate;
import org.skife.jdbi.v2.sqlobject.SqlBatch;
import org.skife.jdbi.v2.sqlobject.customizers.Mapper;
import org.skife.jdbi.v2.sqlobject.mixins.Transactional;

import amberdb.sql.AmberProperty;
import amberdb.sql.Lookups;
import amberdb.sql.PropertyMapper;


public interface AmberDao extends Transactional<AmberDao> {

    /*
     * DB creation operations (DDL)
     */
    
    /*
     * Main tables
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS vertex (" 
            + "id         BIGINT, "
            + "txn_start  BIGINT DEFAULT 0 NOT NULL, " 
            + "txn_end    BIGINT DEFAULT 0 NOT NULL)")
    void createVertexTable();
    
    
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS edge (" 
            + "id         BIGINT, "
            + "txn_start  BIGINT DEFAULT 0 NOT NULL, " 
            + "txn_end    BIGINT DEFAULT 0 NOT NULL, "
            + "v_out      BIGINT, " 
            + "v_in       BIGINT, "
            + "label      VARCHAR(100), " 
            + "edge_order BIGINT)")
    void createEdgeTable();
    
    
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS property (" 
            + "id        BIGINT, "
            + "txn_start BIGINT DEFAULT 0 NOT NULL, " 
            + "txn_end   BIGINT DEFAULT 0 NOT NULL, "
            + "name      VARCHAR(100), " 
            + "type      CHAR(3), "
            + "value     BLOB)")
    void createPropertyTable();
    
    
    /*
     * Session tables
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS sess_vertex ("
            + "s_id       BIGINT, " 
            + "id         BIGINT, "
            + "txn_start  BIGINT DEFAULT 0 NOT NULL, " 
            + "txn_end    BIGINT DEFAULT 0 NOT NULL, "
            + "state      CHAR(3))")
    void createSessionVertexTable();
    
    
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS sess_edge (" 
            + "s_id       BIGINT, "
            + "id         BIGINT, " 
            + "txn_start  BIGINT DEFAULT 0 NOT NULL, "
            + "txn_end    BIGINT DEFAULT 0 NOT NULL, " 
            + "v_out      BIGINT, "
            + "v_in       BIGINT, " 
            + "label      VARCHAR(100), "
            + "edge_order BIGINT, " 
            + "state      CHAR(3))")
    void createSessionEdgeTable();
    
    
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS sess_property ("
            + "s_id      BIGINT, " 
            + "id        BIGINT, "
            + "name      VARCHAR(100), " 
            + "type      CHAR(3), "
            + "value     BLOB)")
    void createSessionPropertyTable();
    
    
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS id_generator ("
            + "id BIGINT PRIMARY KEY AUTO_INCREMENT)")
    void createIdGeneratorTable();
    
    
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS transaction ("
            + "id        BIGINT UNIQUE, " 
            + "time      BIGINT, "
            + "user      VARCHAR(100), " 
            + "operation TEXT)")
    void createTransactionTable();

    
    /*
     * Lookup table - stores lists of objects. for example types of tape
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS list ("
            + "name      VARCHAR(100), " 
            + "value     VARCHAR(100), " 
            + "deleted   VARCHAR(1) )")
    void createListTable();

    /*
     * Tools Lookup table - stores tools related reference data
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS lookups ("
            + "id        int(11), "
            + "name      varchar(50), "
            + "lbl       varchar(255), "
            + "code      varchar(50), "
            + "attribute varchar(255), "
            + "value     blob, "
            + "deleted   varchar(1) )")
    void createToolsLookupTable();
    
    /*
     * Tools Many-To-Many association with multiple material types and software/device category
     */
    @SqlUpdate(
            "CREATE TABLE IF NOT EXISTS maps("
            + "id        int(11), "
            + "parent_id int(11), "        
            + "deleted   varchar(1) )")
    void createToolsMapsTable();   

    /*
     * General lookups
     */
    @SqlUpdate(
      "INSERT INTO list (name, value) VALUES"
      + "('materialType', 'Image'), "
      + "('materialType', 'Sound'),"
      + "('materialType', 'Text' ),"
      + "('copyType', 'Physical'),"
      + "('copyType', 'Digitised'),"
      + "('copyType', 'Born Digital'),"
      + "('copyRole', 'Related metadata'),"
      + "('copyRole', 'RealMedia reference'),"
      + "('copyRole', 'RealMedia file'),"
      + "('copyRole', 'QuickTime reference 1'),"
      + "('copyRole', 'QuickTime reference 2'),"
      + "('copyRole', 'QuickTime reference 3'),"
      + "('copyRole', 'QuickTime reference 4'),"
      + "('copyRole', 'QuickTime file 1'),"
      + "('copyRole', 'QuickTime file 2'),"
      + "('copyRole', 'Original'),"
      + "('copyRole', 'Thumbnail'),"
      + "('copyRole', 'View'),"
      + "('copyRole', 'Examination'),"
      + "('copyRole', 'Master'),"
      + "('copyRole', 'Co-master'),"
      + "('copyRole', 'Archive'),"
      + "('copyRole', 'Summary'),"
      + "('copyRole', 'Transcript'),"
      + "('copyRole', 'Structural map'),"
      + "('copyRole', 'Finding aid'),"
      + "('copyRole', 'Microform'),"
      + "('copyRole', 'Special delivery'),"
      + "('copyRole', 'Listen 1'),"
      + "('copyRole', 'Listen 2'),"
      + "('copyRole', 'Listen 3'),"
      + "('copyRole', 'Finding aid print'),"
      + "('copyRole', 'List'),"
      + "('copyRole', 'Derivative master'),"
      + "('copyRole', 'Analogue distribution'),"
      + "('copyRole', 'Working'),"
      + "('copyRole', 'Digital distribution'),"
      + "('copyRole', 'Time-coded Transcript'),"
      + "('copyRole', 'Print'),"
      + "('carrier', 'File system'),"
      + "('carrier', 'Working Reel'),"
      + "('carrier', 'User Cassette'),"
      + "('carrier', 'Online'),"
      + "('carrier', 'CD-R'),"
      + "('carrier', 'CD-ROM'),"
      + "('carrier', 'Second copy'),"
      + "('carrier', 'CD Archive'),"
      + "('carrier', 'CD Filtered'),"
      + "('carrier', 'Preservation Reel'),"
      + "('carrier', 'Safety DAT'),"
      + "('carrier', 'Cassette A'),"
      + "('carrier', 'Cassette B'),"
      + "('carrier', 'DAT'),"
      + "('carrier', 'Multitrack-ADAT'),"
      + "('carrier', 'Multitrack-DTRS'),"
      + "('carrier', 'Reel A'),"
      + "('carrier', 'Reel B'),"
      + "('carrier', 'CD Duplicate'),"
      + "('carrier', 'User CD'),"
      + "('carrier', 'Second Duplicate'),"
      + "('carrier', 'DVD Archive'),"
      + "('carrier', 'Safety Reel'),"
      + "('carrier', 'Microcassette'),"
      + "('carrier', 'NONE'),"
      + "('acquisitionStatus', 'CURRENT'),"
      + "('acquisitionStatus', 'BACKLOG'),"
      + "('acquisitionStatus', 'MS'),"
      + "('acquisitionCategory', 'Social History'),"
      + "('acquisitionCategory', 'Eminent Australians'),"
      + "('acquisitionCategory', 'Folklore'),"
      + "('acquisitionCategory', 'Others'),"
      + "('segmentIndicator', 'Non-timed'),"
      + "('segmentIndicator', 'Timed'),"
      + "('bitDepth', '8'),"
      + "('bitDepth', '12'),"
      + "('bitDepth', '14'),"
      + "('bitDepth', '16'),"
      + "('bitDepth', '18'),"
      + "('bitDepth', '20'),"
      + "('bitDepth', '22'),"
      + "('bitDepth', '24'),"
      + "('orientation', 'Portrait'),"
      + "('orientation', 'LandscapePortrait'),"
      + "('orientation', 'Landscape'),"
      + "('colourProfile', 'Within image'),"
      + "('colourProfile', 'External'),"
      + "('surface', 'Enhanced Azo'),"
      + "('surface', 'C-CrO2'),"
      + "('surface', 'C-Fe2O3'),"
      + "('surface', 'C-Metal'),"
      + "('surface', 'Cyanine'),"
      + "('surface', 'DOSS'),"
      + "('surface', 'Metal Azo'),"
      + "('surface', 'Pthalocyanine'),"
      + "('surface', 'Pthalocyanine Al T-Acetate'),"
      + "('surface', 'T-Paper'),"
      + "('surface', 'T-Polyester'),"
      + "('surface', 'T-PVC'),"
      + "('surface', 'Unsure'),"
      + "('carrierDuration', '2 min'),"
      + "('carrierDuration', '5 min'),"
      + "('carrierDuration', '12 min'),"
      + "('carrierDuration', '30 min'),"
      + "('carrierDuration', '40 min'),"
      + "('carrierDuration', '45 min'),"
      + "('carrierDuration', '46 min'),"
      + "('carrierDuration', '60 min'),"
      + "('carrierDuration', '63 min'),"
      + "('carrierDuration', '65 min'),"
      + "('carrierDuration', '74 min'),"
      + "('carrierDuration', '80 min'),"
      + "('carrierDuration', '90 min'),"
      + "('carrierDuration', '95 min'),"
      + "('carrierDuration', '96 min'),"
      + "('carrierDuration', '120 min'),"
      + "('carrierDuration', '122 min'),"
      + "('carrierDuration', '125 min'),"
      + "('carrierDuration', '180 min'),"
      + "('carrierDuration', '650 MB'),"
      + "('carrierDuration', '4.7 GB'),"
      + "('reelSize', '2in'),"
      + "('reelSize', '3in IEC'),"
      + "('reelSize', '4in IEC'),"
      + "('reelSize', '5in IEC'),"
      + "('reelSize', '5in NAB'),"
      + "('reelSize', '6in IEC'),"
      + "('reelSize', '7in IEC'),"
      + "('reelSize', '7in NAB'),"
      + "('reelSize', '8.25in IEC'),"
      + "('reelSize', '10in NAB'),"
      + "('reelSize', '10in IEC'),"
      + "('channel', '0.5'),"
      + "('channel', '1'),"
      + "('channel', '2'),"
      + "('channel', '4'),"
      + "('channel', '8'),"
      + "('channel', '16'),"
      + "('channel', '24'),"
      + "('speed', '2.38 cm/s'),"
      + "('speed', '4.76 cm/s'),"
      + "('speed', '9.5 cm/s'),"
      + "('speed', '19.05 cm/s'),"
      + "('speed', '38.1 cm/s'),"
      + "('speed', '76.2 cm/s'),"
      + "('thickness', 'Double play'),"
      + "('thickness', 'Long play'),"
      + "('thickness', 'Standard'),"
      + "('thickness', 'Triple play'),"
      + "('brand', 'EMITAPE 77/6'),"
      + "('brand', 'TDK 150'),"
      + "('brand', 'Scotch 131'),"
      + "('brand', 'AGFA PE 46'),"
      + "('brand', 'ACV'),"
      + "('brand', 'admark'),"
      + "('brand', '3M 807'),"
      + "('brand', 'ACME'),"
      + "('brand', 'AGFA'),"
      + "('brand', 'AGFA CARAT FeCr'),"
      + "('brand', 'AGFA DA DAT'),"
      + "('brand', 'AGFA DAT'),"
      + "('brand', 'AGFA FeI-S'),"
      + "('brand', 'AGFA FERRO COLOR'),"
      + "('brand', 'AGFA FERROCOLOR'),"
      + "('brand', 'AGFA FS'),"
      + "('brand', 'AGFA FS 396'),"
      + "('brand', 'AGFA GEVAERT'),"
      + "('brand', 'AGFA -GEVAERT PE36'),"
      + "('brand', 'AGFA Magnetonband'),"
      + "('brand', 'AGFA Magnetonband PER 525'),"
      + "('brand', 'AGFA PE 31'),"
      + "('brand', 'AGFA PE 36'),"
      + "('brand', 'AGFA PE 38'),"
      + "('brand', 'AGFA PE 4'),"
      + "('brand', 'AGFA PE 41'),"
      + "('brand', 'AGFA PE 65'),"
      + "('brand', 'AGFA PEM 369'),"
      + "('brand', 'AGFA PEM 468'),"
      + "('brand', 'AGFA PEM 469'),"
      + "('brand', 'AGFA PER'),"
      + "('brand', 'AGFA PER 368'),"
      + "('brand', 'AGFA PER 468'),"
      + "('brand', 'AGFA PER 525'),"
      + "('brand', 'AGFA PER 528'),"
      + "('brand', 'AGFA PER 555'),"
      + "('brand', 'AGFA SM'),"
      + "('brand', 'AGFA SUPER C60+6'),"
      + "('brand', 'AGFA SUPER COLOR'),"
      + "('brand', 'AGFA SUPERCHROM'),"
      + "('brand', 'AGFA WOLFEN'),"
      + "('brand', 'AGFA-GEVAERT'),"
      + "('brand', 'AGFA-GEVAERT 65'),"
      + "('brand', 'AGFA-GEVAERT SM'),"
      + "('brand', 'AIWA'),"
      + "('brand', 'AIWA DAT'),"
      + "('brand', 'AKAI'),"
      + "('brand', 'AKAI AT-5S'),"
      + "('brand', 'AKAI Ferro Extra I'),"
      + "('brand', 'AKAI HX'),"
      + "('brand', 'Allegro'),"
      + "('brand', 'ALMAG'),"
      + "('brand', 'ALPHA'),"
      + "('brand', 'AMCOLOR'),"
      + "('brand', 'AMERICAN'),"
      + "('brand', 'American Recording tape'),"
      + "('brand', 'AMPEX'),"
      + "('brand', 'AMPEX 1800'),"
      + "('brand', 'AMPEX 2020'),"
      + "('brand', 'AMPEX 2500'),"
      + "('brand', 'AMPEX 350'),"
      + "('brand', 'AMPEX 370'),"
      + "('brand', 'AMPEX 406'),"
      + "('brand', 'AMPEX 407'),"
      + "('brand', 'AMPEX 431'),"
      + "('brand', 'AMPEX 444'),"
      + "('brand', 'AMPEX 456'),"
      + "('brand', 'AMPEX 457'),"
      + "('brand', 'AMPEX 467 DAT'),"
      + "('brand', 'AMPEX 478'),"
      + "('brand', 'AMPEX 511'),"
      + "('brand', 'AMPEX 521'),"
      + "('brand', 'AMPEX 531'),"
      + "('brand', 'AMPEX 600'),"
      + "('brand', 'Ampex 611'),"
      + "('brand', 'AMPEX 631'),"
      + "('brand', 'AMPEX 632'),"
      + "('brand', 'AMPEX 641'),"
      + "('brand', 'AMPEX 642'),"
      + "('brand', 'AMPEX 679'),"
      + "('brand', 'AMPEX DAT'),"
      + "('brand', 'AMPEX EDR'),"
      + "('brand', 'AMPEX ELN'),"
      + "('brand', 'AMPEX GM'),"
      + "('brand', 'AMPEX GM3600'),"
      + "('brand', 'AMPEX GMI'),"
      + "('brand', 'AMPEX PLUS'),"
      + "('brand', 'AMPEX UDR'),"
      + "('brand', 'Anorgana Geno 1on Typ'),"
      + "('brand', 'Aristocrat'),"
      + "('brand', 'ARMSTRONG AUDIO'),"
      + "('brand', 'Astropulse'),"
      + "('brand', 'AUDIO DIMENSION'),"
      + "('brand', 'Audio Magnetics'),"
      + "('brand', 'AUDIO MAGNETICS CORPORATION'),"
      + "('brand', 'AUDIOMASTERS CORPORATION'),"
      + "('brand', 'AUDIOSONIC'),"
      + "('brand', 'audiotape'),"
      + "('brand', 'audiotape Q19'),"
      + "('brand', 'AUSTRALIAN HANIMEX'),"
      + "('brand', 'AVC'),"
      + "('brand', 'Award'),"
      + "('brand', 'BASF'),"
      + "('brand', 'BASF Chromdioxid'),"
      + "('brand', 'BASF chromdioxid super'),"
      + "('brand', 'BASF Chromdioxid Super II'),"
      + "('brand', 'BASF Chrome Extra II'),"
      + "('brand', 'BASF Chrome MaximaII'),"
      + "('brand', 'BASF CHROME SUPER II'),"
      + "('brand', 'BASF CR-M II'),"
      + "('brand', 'BASF DAT'),"
      + "('brand', 'BASF DP'),"
      + "('brand', 'BASF DP 26'),"
      + "('brand', 'BASF DP 26 LH'),"
      + "('brand', 'BASF DP26'),"
      + "('brand', 'BASF Ferro Extra I'),"
      + "('brand', 'BASF ferro maxima I'),"
      + "('brand', 'BASF Ferro Super I'),"
      + "('brand', 'BASF Ferro Super LH I'),"
      + "('brand', 'BASF ferro super LHI'),"
      + "('brand', 'BASF hifi'),"
      + "('brand', 'BASF LANGSPIELBAND'),"
      + "('brand', 'BASF LGH'),"
      + "('brand', 'BASF LGH 30 P'),"
      + "('brand', 'BASF LGR'),"
      + "('brand', 'BASF LGR 30 P'),"
      + "('brand', 'BASF LGR 35'),"
      + "('brand', 'BASF LGR P'),"
      + "('brand', 'BASF LGR P 30'),"
      + "('brand', 'BASF LGS'),"
      + "('brand', 'BASF LGS 26'),"
      + "('brand', 'BASF LGS 35'),"
      + "('brand', 'BASF LGS 52'),"
      + "('brand', 'BASF LH'),"
      + "('brand', 'BASF LH 90'),"
      + "('brand', 'BASF LH extra I'),"
      + "('brand', 'BASF LH SM'),"
      + "('brand', 'BASF LH Super'),"
      + "('brand', 'BASF LH SUPER 1'),"
      + "('brand', 'BASF LH Super I'),"
      + "('brand', 'BASF LH-EI'),"
      + "('brand', 'BASF LH-MI'),"
      + "('brand', 'BASF LHSM'),"
      + "('brand', 'BASF LN'),"
      + "('brand', 'BASF LN super 1'),"
      + "('brand', 'BASF LN super I'),"
      + "('brand', 'BASF LP'),"
      + "('brand', 'BASF LP35'),"
      + "('brand', 'BASF LPR 35'),"
      + "('brand', 'BASF LR 56'),"
      + "('brand', 'BASF PEM 369'),"
      + "('brand', 'BASF PEM 468'),"
      + "('brand', 'BASF PER 368'),"
      + "('brand', 'BASF PES 18'),"
      + "('brand', 'BASF SM'),"
      + "('brand', 'BASF SM 468'),"
      + "('brand', 'BASF SM 911'),"
      + "('brand', 'BASF SP 52'),"
      + "('brand', 'BASF SP50 LH'),"
      + "('brand', 'BASF SP54 R'),"
      + "('brand', 'BASF SP55 R'),"
      + "('brand', 'BASF SPR 50'),"
      + "('brand', 'BASF SPR 50 LH'),"
      + "('brand', 'BASF SPR 50 LHL'),"
      + "('brand', 'BASF TP 18 LH'),"
      + "('brand', 'BASF TYP LGN'),"
      + "('brand', 'BASF TYP LGS'),"
      + "('brand', 'BASF Typ LGS 26'),"
      + "('brand', 'BASF TYP LGS 52'),"
      + "('brand', 'BEL CLEER'),"
      + "('brand', 'BITCO'),"
      + "('brand', 'Brand 5'),"
      + "('brand', 'Brand Five'),"
      + "('brand', 'CAPITOL'),"
      + "('brand', 'certron'),"
      + "('brand', 'certron HE90'),"
      + "('brand', 'CFS Westinghouse-SPRcolor'),"
      + "('brand', 'Chapple'),"
      + "('brand', 'Compact Cassette'),"
      + "('brand', 'CONCERTAPE'),"
      + "('brand', 'Concorde'),"
      + "('brand', 'CONTRAST'),"
      + "('brand', 'CORONET HE'),"
      + "('brand', 'CORONET LN'),"
      + "('brand', 'Craig'),"
      + "('brand', 'CREST INTERNATIONAL'),"
      + "('brand', 'Crystal'),"
      + "('brand', 'cts'),"
      + "('brand', 'DENON'),"
      + "('brand', 'DENON DX'),"
      + "('brand', 'DENON DX1'),"
      + "('brand', 'DENON DX8'),"
      + "('brand', 'DENON LX'),"
      + "('brand', 'DEUTSCHE WELLE'),"
      + "('brand', 'Dick Smith'),"
      + "('brand', 'DICK SMITH EDR'),"
      + "('brand', 'Dindy'),"
      + "('brand', 'Dindy Black'),"
      + "('brand', 'Dindy Super'),"
      + "('brand', 'Dokorder'),"
      + "('brand', 'Dominion'),"
      + "('brand', 'Douglas Hi-Fi'),"
      + "('brand', 'duCros'),"
      + "('brand', 'EASTMAN KODAK'),"
      + "('brand', 'E-LITE'),"
      + "('brand', 'EMI'),"
      + "('brand', 'EMI Hi dynamic'),"
      + "('brand', 'EMITAPE'),"
      + "('brand', 'EMITAPE 100'),"
      + "('brand', 'EMITAPE 4'),"
      + "('brand', 'EMITAPE 5'),"
      + "('brand', 'EMITAPE 88'),"
      + "('brand', 'EMITAPE 88/12EH'),"
      + "('brand', 'EMITAPE 88/6'),"
      + "('brand', 'EMITAPE Afonic'),"
      + "('brand', 'EMITAPE HI-DYNAMIC'),"
      + "('brand', 'EMITAPE HI-DYNAMIC 9'),"
      + "('brand', 'EMITAPE HI-DYNAMIC HLP-9'),"
      + "('brand', 'EMITAPE HI-DYNAMIC HSP6'),"
      + "('brand', 'EMITAPE MAGNETIC'),"
      + "('brand', 'EMITAPE X1000'),"
      + "('brand', 'ferro MASTER UD'),"
      + "('brand', 'Ferrodynamics'),"
      + "('brand', 'Ferrograph-Ampex'),"
      + "('brand', 'FORWARD'),"
      + "('brand', 'FUJI'),"
      + "('brand', 'FUJI DAT'),"
      + "('brand', 'FUJI DR'),"
      + "('brand', 'FUJI DR-I'),"
      + "('brand', 'FUJI FILM'),"
      + "('brand', 'FUJI FILM FL'),"
      + "('brand', 'FUJI FILM FX'),"
      + "('brand', 'FUJI FL'),"
      + "('brand', 'FUJI FR-I'),"
      + "('brand', 'FUJI FR-I Super'),"
      + "('brand', 'FUJI FX-II'),"
      + "('brand', 'FUJI R DAT'),"
      + "('brand', 'Geloso'),"
      + "('brand', 'Gevaert'),"
      + "('brand', 'glatigny'),"
      + "('brand', 'GOLDRING'),"
      + "('brand', 'GOLDRING STUDIO RANGE'),"
      + "('brand', 'Graceline'),"
      + "('brand', 'GREENCORP'),"
      + "('brand', 'GRUNDIG'),"
      + "('brand', 'Grundig TLP2'),"
      + "('brand', 'GTape'),"
      + "('brand', 'GTape 900'),"
      + "('brand', 'GTape High Density'),"
      + "('brand', 'HANIMEX'),"
      + "('brand', 'HCL'),"
      + "('brand', 'HHB'),"
      + "('brand', 'HHb DA113DC'),"
      + "('brand', 'HITACHI'),"
      + "('brand', 'HITACHI DL'),"
      + "('brand', 'HITACHI Lo-D'),"
      + "('brand', 'HITACHI UD'),"
      + "('brand', 'HITACHI ULTRA'),"
      + "('brand', 'HITACHI ULTRA DYNAMIC'),"
      + "('brand', 'HI-TECH'),"
      + "('brand', 'ILFORD'),"
      + "('brand', 'imation'),"
      + "('brand', 'imitation'),"
      + "('brand', 'INTERNATIONAL'),"
      + "('brand', 'IRISH'),"
      + "('brand', 'IRU'),"
      + "('brand', 'KDK'),"
      + "('brand', 'KGC'),"
      + "('brand', 'KLARION'),"
      + "('brand', 'KODAK'),"
      + "('brand', 'KODAVOX'),"
      + "('brand', 'LAFAYETTE'),"
      + "('brand', 'Lancia'),"
      + "('brand', 'Lectra'),"
      + "('brand', 'LOEWE OPTA'),"
      + "('brand', 'M R SOUNDS'),"
      + "('brand', 'magna MAX2'),"
      + "('brand', 'MAGNASOUND'),"
      + "('brand', 'MALLORY'),"
      + "('brand', 'MARSHAL GOLDEN STUDIO'),"
      + "('brand', 'Marshall'),"
      + "('brand', 'MASTERTAPE'),"
      + "('brand', 'MASTERTONE'),"
      + "('brand', 'MAXELL'),"
      + "('brand', 'Maxell 35-90B'),"
      + "('brand', 'MAXELL A35.5'),"
      + "('brand', 'MAXELL A35-7'),"
      + "('brand', 'Maxell A50.5'),"
      + "('brand', 'maxell E25-7'),"
      + "('brand', 'Maxell LN'),"
      + "('brand', 'maxell MX'),"
      + "('brand', 'maxell S-LN'),"
      + "('brand', 'maxell UD'),"
      + "('brand', 'maxell UDI'),"
      + "('brand', 'maxell UDS-II'),"
      + "('brand', 'maxell UL'),"
      + "('brand', 'maxell UR'),"
      + "('brand', 'maxell XL II'),"
      + "('brand', 'maxell XLI'),"
      + "('brand', 'maxell XLI-S'),"
      + "('brand', 'MAX-WELL'),"
      + "('brand', 'Maxwell MX'),"
      + "('brand', 'Melody'),"
      + "('brand', 'MEMOREX'),"
      + "('brand', 'MEMOREX 1800'),"
      + "('brand', 'MEMOREX MRX 2'),"
      + "('brand', 'MEMOREX MRX I'),"
      + "('brand', 'mfp'),"
      + "('brand', 'MIDAS'),"
      + "('brand', 'MITAPE'),"
      + "('brand', 'MUSICWAY AUDIO'),"
      + "('brand', 'NAGU'),"
      + "('brand', 'NATIONAL'),"
      + "('brand', 'National EN'),"
      + "('brand', 'NATIONAL PANASONIC'),"
      + "('brand', 'NATIONAL PANASONIC RT'),"
      + "('brand', 'NATIONAL RT'),"
      + "('brand', 'NATIONAL RT 3'),"
      + "('brand', 'NATIONAL RT 3G'),"
      + "('brand', 'NATIONAL RT 5'),"
      + "('brand', 'NATIONAL RT-5G'),"
      + "('brand', 'NATIONAL RT-7G'),"
      + "('brand', 'No Frills'),"
      + "('brand', 'NORD'),"
      + "('brand', 'NORD BC'),"
      + "('brand', 'NORDIC'),"
      + "('brand', 'OCL'),"
      + "('brand', 'Olympic Technology'),"
      + "('brand', 'OPUS'),"
      + "('brand', 'OPUS UD'),"
      + "('brand', 'OPUS XD1'),"
      + "('brand', 'Pacific'),"
      + "('brand', 'PARAMOUNT'),"
      + "('brand', 'PDQ'),"
      + "('brand', 'PENNCREST'),"
      + "('brand', 'PERMATION'),"
      + "('brand', 'PERMATON'),"
      + "('brand', 'PHILIPS'),"
      + "('brand', 'PHILIPS AV'),"
      + "('brand', 'PHILIPS DP 13'),"
      + "('brand', 'PHILIPS DP 18'),"
      + "('brand', 'PHILIPS DP13'),"
      + "('brand', 'PHILIPS EL 3915'),"
      + "('brand', 'PHILIPS EL3914'),"
      + "('brand', 'PHILIPS EL3915'),"
      + "('brand', 'PHILIPS ER 13'),"
      + "('brand', 'PHILIPS ER 18'),"
      + "('brand', 'PHILIPS FE'),"
      + "('brand', 'PHILIPS FE I'),"
      + "('brand', 'PHILIPS FS'),"
      + "('brand', 'PHILIPS LP 10'),"
      + "('brand', 'PHILIPS LP 13'),"
      + "('brand', 'PHILIPS LP 15'),"
      + "('brand', 'PHILIPS LP 18'),"
      + "('brand', 'PRINZ'),"
      + "('brand', 'PRO DISC'),"
      + "('brand', 'PULSAR'),"
      + "('brand', 'PURVISONIC'),"
      + "('brand', 'Philips SP18'),"
      + "('brand', 'Pinnacle'),"
      + "('brand', 'PYRAL'),"
      + "('brand', 'PYROX'),"
      + "('brand', 'PYROX MAGICTAPE'),"
      + "('brand', 'QANTEM'),"
      + "('brand', 'QUANTEGY'),"
      + "('brand', 'RADIANT'),"
      + "('brand', 'Radio Shack'),"
      + "('brand', 'rainbow'),"
      + "('brand', 'Ralec'),"
      + "('brand', 'RALMAR'),"
      + "('brand', 'RALMER'),"
      + "('brand', 'RCA'),"
      + "('brand', 'RCA RED SEAL'),"
      + "('brand', 'REALISTIC'),"
      + "('brand', 'REALISTIC GOLD'),"
      + "('brand', 'REALISTIC LN'),"
      + "('brand', 'REALISTIC SUPERTAPE GOLD'),"
      + "('brand', 'recoton'),"
      + "('brand', 'Red Seal'),"
      + "('brand', 'ROBINS'),"
      + "('brand', 'ROLA'),"
      + "('brand', 'ROLATAPE'),"
      + "('brand', 'ROSS'),"
      + "('brand', 'ROYAL APC'),"
      + "('brand', 'RTC Playrite'),"
      + "('brand', 'RZ'),"
      + "('brand', 'SAISHO'),"
      + "('brand', 'SANYO'),"
      + "('brand', 'SAST'),"
      + "('brand', 'Scotch'),"
      + "('brand', 'Scotch 102'),"
      + "('brand', 'Scotch 111'),"
      + "('brand', 'Scotch 111A'),"
      + "('brand', 'Scotch 150'),"
      + "('brand', 'Scotch 175'),"
      + "('brand', 'Scotch 176'),"
      + "('brand', 'Scotch 177'),"
      + "('brand', 'Scotch 190'),"
      + "('brand', 'Scotch 200'),"
      + "('brand', 'Scotch 202'),"
      + "('brand', 'Scotch 203'),"
      + "('brand', 'Scotch 206'),"
      + "('brand', 'Scotch 207'),"
      + "('brand', 'Scotch 208'),"
      + "('brand', 'Scotch 215'),"
      + "('brand', 'Scotch 250'),"
      + "('brand', 'Scotch 9008'),"
      + "('brand', 'Scotch AV 177'),"
      + "('brand', 'Scotch Boy'),"
      + "('brand', 'Scotch BX'),"
      + "('brand', 'Scotch CLASSIC'),"
      + "('brand', 'Scotch DYNARANGE'),"
      + "('brand', 'Scotch Master'),"
      + "('brand', 'Scotch RB-5'),"
      + "('brand', 'Shamrock'),"
      + "('brand', 'SHARP'),"
      + "('brand', 'SILVER SONIC'),"
      + "('brand', 'silver sound'),"
      + "('brand', 'Silver TRAK UDX'),"
      + "('brand', 'Soni-Tape'),"
      + "('brand', 'SONOCOLOR'),"
      + "('brand', 'SONY'),"
      + "('brand', 'SONY 100'),"
      + "('brand', 'SONY 60'),"
      + "('brand', 'SONY AHF'),"
      + "('brand', 'SONY BHF'),"
      + "('brand', 'SONY C'),"
      + "('brand', 'SONY CHF'),"
      + "('brand', 'SONY DAT'),"
      + "('brand', 'SONY DC'),"
      + "('brand', 'SONY DT DAT'),"
      + "('brand', 'SONY EF'),"
      + "('brand', 'SONY HF'),"
      + "('brand', 'SONY PDP-65'),"
      + "('brand', 'SONY PDP-65C'),"
      + "('brand', 'SONY PR-150'),"
      + "('brand', 'SONY SUPER 150'),"
      + "('brand', 'SONY SUPER 300'),"
      + "('brand', 'SONY UCX'),"
      + "('brand', 'SONY UCX-S'),"
      + "('brand', 'SONY ULH'),"
      + "('brand', 'SONY UX'),"
      + "('brand', 'SONY UX-S'),"
      + "('brand', 'SONY ZX'),"
      + "('brand', 'SOUNDCRAFT'),"
      + "('brand', 'Star'),"
      + "('brand', 'STUDER'),"
      + "('brand', 'SUMMIT'),"
      + "('brand', 'Sunhing'),"
      + "('brand', 'SUPERTAPE GOLD'),"
      + "('brand', 'SUPERTAPE HD'),"
      + "('brand', 'SWEDA'),"
      + "('brand', 'T.D.J'),"
      + "('brand', 'TAMMY'),"
      + "('brand', 'tandberg radio'),"
      + "('brand', 'TARGET'),"
      + "('brand', 'TDK'),"
      + "('brand', 'TDK 90'),"
      + "('brand', 'TDK AD'),"
      + "('brand', 'TDK ADX'),"
      + "('brand', 'TDK AR'),"
      + "('brand', 'TDK ARX'),"
      + "('brand', 'TDK C'),"
      + "('brand', 'TDK D'),"
      + "('brand', 'TDK DA-R DAT'),"
      + "('brand', 'TDK DA-RXG'),"
      + "('brand', 'TDK F'),"
      + "('brand', 'TDK LN'),"
      + "('brand', 'TDK LX 35'),"
      + "('brand', 'TDK MA-R'),"
      + "('brand', 'TDK MA-X'),"
      + "('brand', 'TDK OD'),"
      + "('brand', 'TDK RC2'),"
      + "('brand', 'TDK SA'),"
      + "('brand', 'TDK SA-X'),"
      + "('brand', 'TDK SD'),"
      + "('brand', 'TDK SF'),"
      + "('brand', 'TDK Super Dynamic 1200 - SD'),"
      + "('brand', 'That''s'),"
      + "('brand', 'TDK Super Dynamic 1200-SD'),"
      + "('brand', 'TDK-E Synchroreel'),"
      + "('brand', 'TEAC'),"
      + "('brand', 'TEAC SOUND 52'),"
      + "('brand', 'TELEX'),"
      + "('brand', 'TEMPEST'),"
      + "('brand', 'That''s'),"
      + "('brand', 'thunder'),"
      + "('brand', 'TIANTAN'),"
      + "('brand', 'TONEX'),"
      + "('brand', 'TONEX Pastels'),"
      + "('brand', 'Toshiba'),"
      + "('brand', 'Tower'),"
      + "('brand', 'TRANSONIC'),"
      + "('brand', 'tronictape'),"
      + "('brand', 'TSL D'),"
      + "('brand', 'Ultra Sound'),"
      + "('brand', 'Unic'),"
      + "('brand', 'Unknown'),"
      + "('brand', 'VERBATIM'),"
      + "('brand', 'VIbrant'),"
      + "('brand', 'VIVA'),"
      + "('brand', 'W & G'),"
      + "('brand', 'WHSMITH'),"
      + "('brand', 'WORLD SLN'),"
      + "('brand', 'YASHIMA UFOI'),"
      + "('brand', 'ZENITH'),"
      + "('brand', 'EMITAPE 99'),"
      + "('brand', 'TEAC CDX'),"
      + "('brand', 'Dictasette'),"
      + "('brand', 'Zonal'),"
      + "('brand', 'TDK GX 35-90B'),"
      + "('brand', 'AMPEX 541'),"
      + "('brand', 'AMPEX 434'),"
      + "('brand', 'ORWO CR 35'),"
      + "('brand', 'Scotch RB-7'),"
      + "('brand', 'Scotch 220'),"
      + "('brand', 'PHILLIPS CD'),"
      + "('brand', 'ORWO'),"
      + "('brand', 'EMI Super'),"
      + "('brand', 'esc'),"
      + "('brand', 'BASF Ferro POWER I'),"
      + "('brand', 'TDK LX 50-60B'),"
      + "('brand', 'JVC MC-60SF'),"
      + "('durationType', 'Default'),"
      + "('durationType', 'Input'),"
      + "('equalisation', 'IEC'),"
      + "('equalisation', 'NAB'),"
      + "('samplingRate', '11000'),"
      + "('samplingRate', '22050'),"
      + "('samplingRate', '24000'),"
      + "('samplingRate', '32000'),"
      + "('samplingRate', '44100'),"
      + "('samplingRate', '48000'),"
      + "('samplingRate', '88200'),"
      + "('samplingRate', '96000'),"
      + "('samplingRate', '176400'),"
      + "('samplingRate', '192000'),"
      + "('soundField', 'Stereo'),"
      + "('soundField', 'Mono'),"
      + "('collection','Australian'),"
      + "('collection','Manuscript'),"
      + "('collection','Map'),"
      + "('collection','Music'),"
      + "('collection','Picture'),"
      + "('collection','General'),"
      + "('collection','Oral history and folklore'),"
      + "('collection','Internal photograph'),"
      + "('collection','Conservation'),"
      + "('subUnitType','Additional Material'),"
      + "('subUnitType','Attachment'),"
      + "('subUnitType','Bibliography'),"
      + "('subUnitType','Biography'),"
      + "('subUnitType','Board leaf'),"
      + "('subUnitType','Book'),"
      + "('subUnitType','Booklet'),"
      + "('subUnitType','Box'),"
      + "('subUnitType','Chapter'),"
      + "('subUnitType','Clipping'),"
      + "('subUnitType','Cover'),"
      + "('subUnitType','Cover - Back'),"
      + "('subUnitType','Cover - Front'),"
      + "('subUnitType','Cover - Inside Front '),"
      + "('subUnitType','Cover - Variant'),"
      + "('subUnitType','Cover - Inside Back '),"
      + "('subUnitType','Dedication'),"
      + "('subUnitType','Discography'),"
      + "('subUnitType','Enclosure'),"
      + "('subUnitType','End Papers'),"
      + "('subUnitType','Envelope'),"
      + "('subUnitType','Fly Leaf'),"
      + "('subUnitType','Folder'),"
      + "('subUnitType','Folio'),"
      + "('subUnitType','Foredge'),"
      + "('subUnitType','Game board'),"
      + "('subUnitType','Game instructions'),"
      + "('subUnitType','Game pieces'),"
      + "('subUnitType','Head'),"
      + "('subUnitType','Illustration'),"
      + "('subUnitType','Index'),"
      + "('subUnitType','Introduction'),"
      + "('subUnitType','Invitation'),"
      + "('subUnitType','Item'),"
      + "('subUnitType','Map'),"
      + "('subUnitType','Number'),"
      + "('subUnitType','Obverse'),"
      + "('subUnitType','Page'),"
      + "('subUnitType','Page - Additional'),"
      + "('subUnitType','Page - Additional Title'),"
      + "('subUnitType','Page - Contents '),"
      + "('subUnitType','Page - List Title'),"
      + "('subUnitType','Page - Title '),"
      + "('subUnitType','Page - Unnumbered'),"
      + "('subUnitType','Part'),"
      + "('subUnitType','Plate'),"
      + "('subUnitType','Plate - Leaf'),"
      + "('subUnitType','Plate - Verso'),"
      + "('subUnitType','Plates - List'),"
      + "('subUnitType','Port'),"
      + "('subUnitType','Preface'),"
      + "('subUnitType','Program'),"
      + "('subUnitType','Recto'),"
      + "('subUnitType','Reverse'),"
      + "('subUnitType','Section'),"
      + "('subUnitType','Series'),"
      + "('subUnitType','Session'),"
      + "('subUnitType','Spine'),"
      + "('subUnitType','State'),"
      + "('subUnitType','Subseries'),"
      + "('subUnitType','Table Of Contents'),"
      + "('subUnitType','Tail'),"
      + "('subUnitType','Text block'),"
      + "('subUnitType','Tile'),"
      + "('subUnitType','Title page verso'),"
      + "('subUnitType','Tour'),"
      + "('subUnitType','Verso'),"
      + "('subUnitType','Volume'),"
      + "('form','Book'),"
      + "('form','Manuscript'),"
      + "('form','Map'),"
      + "('form','Music'),"
      + "('form','Picture'),"
      + "('form','Serial'),"
      + "('form','Sound recording'),"
      + "('form','Other - Australian'),"
      + "('form','Other - General'),"
      + "('form','Internal photograph'),"
      + "('form','Conservation'),"
      + "('bibLevel','Set'),"
      + "('bibLevel','Item'),"
      + "('bibLevel','Part'),"
      + "('digitalStatus','Captured'),"
      + "('digitalStatus','Not Captured'),"
      + "('digitalStatus','Partially Captured'),"
      + "('digitalStatus','Preserved analogue'),"
      + "('encodingLevel','Master Copy'),"
      + "('encodingLevel','# - Full level'),"
      + "('encodingLevel','1 - Full level, material not examined'),"
      + "('encodingLevel','2 - Less-than-full level, material not examined'),"
      + "('encodingLevel','3 - Abbreviated level'),"
      + "('encodingLevel','4 - Core level'),"
      + "('encodingLevel','5 - Partial (preliminary) level'),"
      + "('encodingLevel','7 - Minimal level'),"
      + "('encodingLevel','8 - Prepublication level'),"
      + "('encodingLevel','u - Unknown'),"
      + "('encodingLevel','z - Not applicable'),"
      + "('encodingLevel','None'),"
      + "('encodingLevel','Card only'),"
      + "('encodingLevel','Collection level'),"
      + "('encodingLevel','Collection in process'),"
      + "('encodingLevel','Conditions vary'),"
      + "('encodingLevel','Full in process'),"
      + "('encodingLevel','nothing'),"
      + "('genre','Interview'),"
      + "('genre','Speech'),"
      + "('genre','Conference'),"
      + "('genre','Festival'),"
      + "('genre','Lecture'),"
      + "('genre','Monologue'),"
      + "('genre','Other'),"
      + "('publicationCategory','Press Club'),"
      + "('publicationCategory','Radio'),"
      + "('publicationCategory','Commercial'),"
      + "('publicationCategory','Master Copy'),"
      + "('publicationCategory','Other Press Club'),"
      + "('publicationCategory','Radio'),"
      + "('publicationCategory','Commercial'),"
      + "('publicationCategory','Master Copy'),"
      + "('publicationCategory','Other'),"
      + "('subject','National Library - Products'),"
      + "('subject','National Library - Tapestries'),"
      + "('subject','National Library - Volunteers - [name]'),"
      + "('subject','National Library - Publications - [name]'),"
      + "('subject','National Library - Volunteers - [name]'),"
      + "('subject','National Library - Visits - [name]'),"
      + "('subject','National Library - Building - Exterior - Art'),"
      + "('subject','National Library - Building - Exterior - 1990s'),"
      + "('subject','National Library - Building - Exterior - 2000s'),"
      + "('subject','National Library - Building - Exterior - 2010s'),"
      + "('subject','National Library - Building - Interior - [name]'),"
      + "('subject','National Library - Building - Warehouses and Annexes'),"
      + "('subject','National Library - Committees - [name]'),"
      + "('subject','National Library - Conferences/Seminars/Workshops - [name]'),"
      + "('subject','National Library - Consultants and Contractors - [name]'),"
      + "('subject','National Library - Council - Group and General Photographs'),"
      + "('subject','National Library - Council - Portrait of Individual Member - [name]'),"
      + "('subject','National Library - Donors - [name]'),"
      + "('subject','National Library - Events - [name]'),"
      + "('subject','National Library - Exhibitions - [name]'),"
      + "('subject','National Library - Exhibitions - National Treasures from Australia''s Great Libraries'),"
      + "('subject','National Library - Friends'),"
      + "('subject','National Library - Harold White Fellows - [name]'),"
      + "('subject','National Library - Kenneth Myer Lecture'),"
      + "('subject','National Library - National Folk Festival Fellows - [name]'),"
      + "('subject','National Library - Norman McCann Summer Scholars - [name]'),"
      + "('subject','National Library - Oral History Interview - [name of interviewee]'),"
      + "('subject','National Library - Staff - [name]'),"
      + "('subject','[Institution] - Collection material'),"
      + "('subject','National Library - Social Club'),"
      + "('subject','Events outside the National Library - [name]'),"
      + "('constraint','Copyright'),"
      + "('constraint','Adult content'),"
      + "('constraint','Indigenous'),"
      + "('constraint','Free-of-charge'),"
      + "('constraint','Pending'),"
      + "('constraint','Written permission required'),"
      + "('constraint','Thumbnails only'),"
      + "('constraint','Closed'),"
      + "('constraint','Indigenous - male'),"
      + "('digitalStatus','Captured'),"
      + "('digitalStatus','Not Captured'),"
      + "('digitalStatus','Partially Captured'),"
      + "('digitalStatus','Preserved analogue')"
    )
    void seedListTable();
    
    /*
     * tools name attributes definition
     */
    @SqlUpdate(
            "INSERT INTO lookups(id, name, attribute, value) VALUES"
            + "(1,'tools','name','UMAX PowerLook 2100XL'), "
            + "(2,'tools','name','Scanview ScanMate F6'), "
            + "(3,'tools','name','AGFA Arcus II'), "
            + "(4,'tools','name','AGFA DuoScan T2000XL + FotoLook'), "
            + "(5,'tools','name','Nikon Super CoolScan 4000ED'), "
            + "(6,'tools','name','PhaseOne Phase FX'), "
            + "(7,'tools','name','Sinar Macroscan'), "
            + "(8,'tools','name','Nikon D1'), "
            + "(9,'tools','name','Canon 20D'), "
            + "(10,'tools','name','Kodak ProBack'), "
            + "(11,'tools','name','Canon PS-20'), "
            + "(12,'tools','name','ScanMaker 9600XL'), "
            + "(13,'tools','name','Adobe PhotoShop 5.5'), "
            + "(14,'tools','name','Adobe PhotoShop 6.0'), "
            + "(15,'tools','name','Adobe PhotoShop 6.01'), "
            + "(21,'tools','name','Microtek ArtixScan 2020 + ScanWizard Pro'), "
            + "(22,'tools','name','Nikon Super CoolScan 8000ED + Nikon Scan 4.0'), "
            + "(23,'tools','name','Adobe PhotoShop 7.0'), "
            + "(41,'tools','name','Adobe PhotoShop 7.0.1'), "
            + "(61,'tools','name','Image Robot v1.21'), "
            + "(81,'tools','name','ImageMagick 5.3.8'), "
            + "(82,'tools','name','Image Alchemy 1.12'), "
            + "(101,'tools','name','Image Alchemy 1.13'), "
            + "(102,'tools','name','ImageMagick 5.5.2'), "
            + "(121,'tools','name','SunRise SRI-P150'), "
            + "(141,'tools','name','Canon 10D'), "
            + "(142,'tools','name','ThumbsPlus 5.01'), "
            + "(143,'tools','name','Microtek ArtixScan 2020 + Silverfast'), "
            + "(145,'tools','name','Nikon Super CoolScan 8000ED + Silverfast'), "
            + "(163,'tools','name','Nikon F90X'), "
            + "(183,'tools','name','Other device'), "
            + "(184,'tools','name','Unknown capture device + software'), "
            + "(203,'tools','name','Adobe Photoshop CS'), "
            + "(204,'tools','name','CD-Inspector'), "
            + "(205,'tools','name','DAT-Inspector'), "
            + "(206,'tools','name','Apogee PSX-100'), "
            + "(207,'tools','name','Apogee PSX-100'), "
            + "(208,'tools','name','RME DIGI96/8 Pro'), "
            + "(212,'tools','name','ThumbsPlus v.5.01'), "
            + "(213,'tools','name','Imageware Bookeye Scanner'), "
            + "(214,'tools','name','BCS-2 v2.97'), "
            + "(215,'tools','name','Nakamichi 582'), "
            + "(216,'tools','name','NEUMANN 69fet'), "
            + "(217,'tools','name','NEUMANN KM140'), "
            + "(218,'tools','name','NEUMANN SKM140'), "
            + "(219,'tools','name','NEUMANN TLM170i'), "
            + "(220,'tools','name','NEUMANN U87Ai'), "
            + "(221,'tools','name','NEUMANN U87Ai;NEUMANN 69fet'), "
            + "(222,'tools','name','Otari MX5050B2HD'), "
            + "(223,'tools','name','Plextor CD-R PX-W1210S'), "
            + "(224,'tools','name','Plextor CD-ROM PX-40TS'), "
            + "(225,'tools','name','Revox B77 MkII'), "
            + "(226,'tools','name','Sennheiser MKH-40'), "
            + "(227,'tools','name','Shure WL-185'), "
            + "(228,'tools','name','Sony PCM-7010'), "
            + "(229,'tools','name','Sony PCM-R700'), "
            + "(230,'tools','name','Studer A807'), "
            + "(231,'tools','name','Studer A820'), "
            + "(232,'tools','name','Studer A820'), "
            + "(233,'tools','name','Studer A820'), "
            + "(234,'tools','name','Studer Revox C274'), "
            + "(235,'tools','name','Tascam 122 MkIII'), "
            + "(236,'tools','name','Tascam 122 MkIII'), "
            + "(237,'tools','name','Tascam 122 MkIII'), "
            + "(238,'tools','name','TASCAM DA-98HR'), "
            + "(239,'tools','name','Apogee PSX-100'), "
            + "(240,'tools','name','Apogee PSX-100'), "
            + "(241,'tools','name','Apogee PSX-100'), "
            + "(242,'tools','name','Nagra V'), "
            + "(243,'tools','name','Apogee PSX-100'), "
            + "(244,'tools','name','Sinar 54H'), "
            + "(245,'tools','name','Studer A807'), "
            + "(246,'tools','name','Digital Audio Denmark ADDA 2402'), "
            + "(247,'tools','name','RME Digi 96/8 PAD'), "
            + "(248,'tools','name','Tascam 122 MkIII'), "
            + "(249,'tools','name','Unknown image processing software'), "
            + "(251,'tools','name','Tascam 122'), "
            + "(252,'tools','name','Tascam 122'), "
            + "(253,'tools','name','Tascam 122'), "
            + "(254,'tools','name','Tascam 122 MkII'), "
            + "(255,'tools','name','Revox B77 MkII'), "
            + "(256,'tools','name','Tascam 122 MkIII'), "
            + "(257,'tools','name','Studer A80 MkII'), "
            + "(258,'tools','name','Apogee PSX-100'), "
            + "(259,'tools','name','Digital Audio Denmark ADDA 2402'), "
            + "(260,'tools','name','RME Digi96/8'), "
            + "(261,'tools','name','Digital Audio Denmark ADDA 2402'), "
            + "(262,'tools','name','Revox A77'), "
            + "(263,'tools','name','Sony APR-5003'), "
            + "(264,'tools','name','Sony CYPERSHOT -model?'), "
            + "(265,'tools','name','Canon 1Ds'), "
            + "(266,'tools','name','Canon PowerShot G3'), "
            + "(267,'tools','name','Canon 1Ds MkII'), "
            + "(268,'tools','name','Creo iQsmart2'), "
            + "(269,'tools','name','oXYgen'), "
            + "(270,'tools','name','Sony APR - 5003'), "
            + "(271,'tools','name','RME HDSP9632'), "
            + "(272,'tools','name','Nikon D1x'), "
            + "(273,'tools','name','Apogee Mini-Me'), "
            + "(274,'tools','name','Apogee Mini-Me'), "
            + "(275,'tools','name','Apogee Mini-Me'), "
            + "(276,'tools','name','Apogee Mini-Me'), "
            + "(277,'tools','name','Unknown'), "
            + "(278,'tools','name','Apogee Mini-Me'), "
            + "(279,'tools','name','Nagra V'), "
            + "(280,'tools','name','Sony DSC-V1 '), "
            + "(281,'tools','name','Sony DSC-V1 '), "
            + "(282,'tools','name','Sound Devices 722'), "
            + "(285,'tools','name','Sound Devices 722'), "
            + "(286,'tools','name','Sound Devices 722'), "
            + "(287,'tools','name','Sound Devices 722'), "
            + "(288,'tools','name','Sound Devices 722'), "
            + "(290,'tools','name','Canon 1D MkII'), "
            + "(291,'tools','name','asetf'), "
            + "(293,'tools','name','XNView'), "
            + "(295,'tools','name','Minolta PS 7000'), "
            + "(296,'tools','name','Paper Port'), "
            + "(297,'tools','name','Ariel'), "
            + "(298,'tools','name','Tascam 122 MkIII'), "
            + "(300,'tools','name','Sound Devices 722'), "
            + "(301,'tools','name','Sound Devices 722'), "
            + "(302,'tools','name','Sound Devices 722'), "
            + "(303,'tools','name','Sound Devices 722'), "
            + "(304,'tools','name','Sound Devices 722'), "
            + "(305,'tools','name','Apogee Mini-Me'), "
            + "(306,'tools','name','Kodak Z740'), "
            + "(307,'tools','name','Creo iQsmart1'), "
            + "(308,'tools','name','Fuji FinePix S5000 '), "
            + "(309,'tools','name','Ricoh IS330DC A3'), "
            + "(310,'tools','name','Digital Audio Denmark ADDA 2402'), "
            + "(311,'tools','name','Studer A810'), "
            + "(312,'tools','name','Creo iQsmart 3'), "
            + "(313,'tools','name','Sound Devices 722'), "
            + "(314,'tools','name','Sound Devices 722'), "
            + "(315,'tools','name','Sound Devices 722'), "
            + "(316,'tools','name','Sound Devices 722'), "
            + "(317,'tools','name','Sound Devices 722'), "
            + "(318,'tools','name','Sound Devices 722'), "
            + "(319,'tools','name','Tascam 122 MkIII'), "
            + "(320,'tools','name','Adobe Photoshop CS 2'), "
            + "(321,'tools','name','Sound Devices 722'), "
            + "(322,'tools','name','Sound Devices 722'), "
            + "(323,'tools','name','Sinar Evo 75'), "
            + "(324,'tools','name','Digital Audio Denmark ADDA AX24'), "
            + "(325,'tools','name','Digital Audio Denmark ADDA AX24'), "
            + "(326,'tools','name','Merging Mykerinos MYK-MB5 RevE (WDM)'), "
            + "(327,'tools','name','Digital Audio Denmark ADDA AX24'), "
            + "(328,'tools','name','Digital Audio Denmark ADDA AX24'), "
            + "(329,'tools','name','Colortrac SmartlF 4080'), "
            + "(330,'tools','name','Canon 1DmkIII'), "
            + "(331,'tools','name','Studer A812'), "
            + "(332,'tools','name','Betterlight 10K-HS'), "
            + "(334,'tools','name','Sound Devices 722'), "
            + "(335,'tools','name','Sound Devices 722'), "
            + "(336,'tools','name','Sound Devices 722'), "
            + "(337,'tools','name','Sound Devices 722'), "
            + "(338,'tools','name','Sound Devices 722'), "
            + "(339,'tools','name','PHILIPS DVD+-RW DVD8801'), "
            + "(340,'tools','name','Adobe Photoshop CS3'), "
            + "(341,'tools','name','Sound Devices 722'), "
            + "(342,'tools','name','RME HDSPe AES-32'), "
            + "(343,'tools','name','Digital Audio Denmark ADDA AX24'), "
            + "(344,'tools','name','Canon 1DS MkIII'), "
            + "(346,'tools','name','Dobbin Version 1.0.03'), "
            + "(347,'tools','name','Rode NT-4'), "
            + "(349,'tools','name','Tascam 122 MkII'), "
            + "(350,'tools','name','Studer A807'), "
            + "(351,'tools','name','Studer A67'), "
            + "(352,'tools','name','Studer A820'), "
            + "(353,'tools','name','Adobe Photoshop CS4'), "
            + "(354,'tools','name','Sony PCM-7040'), "
            + "(355,'tools','name','Sony PCM-7040'), "
            + "(356,'tools','name','Sony PCM-7040'), "
            + "(357,'tools','name','Sony PCM-7040'), "
            + "(358,'tools','name','Flextight XI '), "
            + "(359,'tools','name','Sound Devices 722'), "
            + "(360,'tools','name','Sound Devices 722'), "
            + "(361,'tools','name','Sound Devices 722'), "
            + "(362,'tools','name','Sound Devices 722'), "
            + "(363,'tools','name','Sound Devices 722'), "
            + "(364,'tools','name','Tascam 122 MkII'), "
            + "(365,'tools','name','Tascam 122 MkIII'), "
            + "(366,'tools','name','Sony PCM-7040'), "
            + "(367,'tools','name','Sony PCM-7040'), "
            + "(368,'tools','name','CREO iQsmart 3'), "
            + "(369,'tools','name','SMA 21'), "
            + "(370,'tools','name','Ricoh IS330DC '), "
            + "(371,'tools','name','Ricoh IS330DC '), "
            + "(372,'tools','name','Ricoh IS330DC '), "
            + "(373,'tools','name','Ricoh IS330DC '), "
            + "(374,'tools','name','Capture One'), "
            + "(377,'tools','name','PhaseOne P65+'), "
            + "(378,'tools','name','Fostex FR-2'), "
            + "(380,'tools','name','Rode NT5'), "
            + "(381,'tools','name','Canon EOS 5D Mark II'), "
            + "(382,'tools','name','Next Scan'), "
            + "(383,'tools','name','NextStar V.1.02'), "
            + "(384,'tools','name','Tascam 122 MkIII'), "
            + "(385,'tools','name','Tascam 122 MkIII'), "
            + "(386,'tools','name','Tascam 122 MkII'), "
            + "(387,'tools','name','Adobe Photoshop CS5'), "
            + "(388,'tools','name','Creo iQsmart 3'), "
            + "(390,'tools','name','Sound Devices 722'), "
            + "(391,'tools','name','Sound Devices 722'), "
            + "(392,'tools','name','Sound Devices 722'), "
            + "(393,'tools','name','Sound Devices 722'), "
            + "(394,'tools','name','Sound Devices 744T'), "
            + "(395,'tools','name','Sony BM-840T'), "
            + "(396,'tools','name','Sound Devices 722'), "
            + "(397,'tools','name','iText 5.0.6'), "
            + "(398,'tools','name','Tascam 122 MkIII'), "
            + "(400,'tools','name','Sony PCM-R700'), "
            + "(401,'tools','name','Sony PCM-R700'), "
            + "(402,'tools','name','Studio C Quadriga Multiple Ingest Module'), "
            + "(404,'tools','name','Sinar Evo 86H'), "
            + "(405,'tools','name','Canon 1DmkIV'), "
            + "(406,'tools','name','PhaseOne P65'), "
            + "(408,'tools','name','Canon 1D MkIV'), "
            + "(412,'tools','name','Sound Devices 722'), "
            + "(413,'tools','name','Sound Devices 722'), "
            + "(414,'tools','name','Sound Devices 722'), "
            + "(415,'tools','name','RME HDSP AES-32'), "
            + "(417,'tools','name','Rosendahl Nanosyncs HD; H 01668; Digital Audio Denmark ADDA AX24'), "
            + "(418,'tools','name','Rosendahl Nanosyncs HD; H 01668; Digital Audio Denmark ADDA AX24'), "
            + "(422,'tools','name','Sound Devices 744T'), "
            + "(424,'tools','name','V-Scan Cobra book scanner'), "
            + "(425,'tools','name','Canon 1DX'), "
            + "(428,'tools','name','Sony PCM-7040'), "
            + "(429,'tools','name','Studer A820'), "
            + "(430,'tools','name','Tascam 122 MkIII'), "
            + "(431,'tools','name','Guardian AO'), "
            + "(432,'tools','name','Sinar eXact'), "
            + "(433,'tools','name','Studer A820'), "
            + "(436,'tools','name','Hasselblad H4D-200MS'), "
            + "(437,'tools','name','Sound Devices USBPre 2'), "
            + "(438,'tools','name','Tascam 122 MkIII'), "
            + "(439,'tools','name','Futjitsu FI 6770'), "
            + "(440,'tools','name','Cobra Overhead Scanner'), "
            + "(441,'tools','name','Canon DR7090C'), "
            + "(442,'tools','name','ScanPro 2000'), "
            + "(443,'tools','name','Colortrac SmartLF Gx + T42'), "
            + "(444,'tools','name',''), "
            + "(445,'tools','name','Adobe Bridge CS6'), "
            + "(446,'tools','name','Adobe Photoshop CS6')"
            )
    void seedToolsLookupsNameAttribute();
    
    /*
     * tools resolution attributes definitions
     */
    @SqlUpdate(
            "INSERT INTO lookups(id, name, attribute, value) VALUES"
            + "(1,'tools','resolution',''),"
            + "(2,'tools','resolution',''),"
            + "(3,'tools','resolution',''),"
            + "(4,'tools','resolution',''),"
            + "(5,'tools','resolution',''),"
            + "(6,'tools','resolution',''),"
            + "(7,'tools','resolution',''),"
            + "(8,'tools','resolution',''),"
            + "(9,'tools','resolution',''),"
            + "(10,'tools','resolution',''),"
            + "(11,'tools','resolution',''),"
            + "(12,'tools','resolution',''),"
            + "(13,'tools','resolution',''),"
            + "(14,'tools','resolution',''),"
            + "(15,'tools','resolution',''),"
            + "(21,'tools','resolution',''),"
            + "(22,'tools','resolution',''),"
            + "(23,'tools','resolution',''),"
            + "(41,'tools','resolution',''),"
            + "(61,'tools','resolution',''),"
            + "(81,'tools','resolution',''),"
            + "(82,'tools','resolution',''),"
            + "(101,'tools','resolution',''),"
            + "(102,'tools','resolution',''),"
            + "(121,'tools','resolution','400PPI  back to full size of original'),"
            + "(141,'tools','resolution',''),"
            + "(142,'tools','resolution',''),"
            + "(143,'tools','resolution',''),"
            + "(145,'tools','resolution',''),"
            + "(163,'tools','resolution',''),"
            + "(183,'tools','resolution','unknown'),"
            + "(184,'tools','resolution',''),"
            + "(203,'tools','resolution',''),"
            + "(204,'tools','resolution',''),"
            + "(205,'tools','resolution',''),"
            + "(206,'tools','resolution',''),"
            + "(207,'tools','resolution',''),"
            + "(208,'tools','resolution',''),"
            + "(212,'tools','resolution',''),"
            + "(213,'tools','resolution',''),"
            + "(214,'tools','resolution',''),"
            + "(215,'tools','resolution',''),"
            + "(216,'tools','resolution',''),"
            + "(217,'tools','resolution',''),"
            + "(218,'tools','resolution',''),"
            + "(219,'tools','resolution',''),"
            + "(220,'tools','resolution',''),"
            + "(221,'tools','resolution',''),"
            + "(222,'tools','resolution',''),"
            + "(223,'tools','resolution',''),"
            + "(224,'tools','resolution',''),"
            + "(225,'tools','resolution',''),"
            + "(226,'tools','resolution',''),"
            + "(227,'tools','resolution',''),"
            + "(228,'tools','resolution',''),"
            + "(229,'tools','resolution',''),"
            + "(230,'tools','resolution',''),"
            + "(231,'tools','resolution',''),"
            + "(232,'tools','resolution',''),"
            + "(233,'tools','resolution',''),"
            + "(234,'tools','resolution',''),"
            + "(235,'tools','resolution',''),"
            + "(236,'tools','resolution',''),"
            + "(237,'tools','resolution',''),"
            + "(238,'tools','resolution',''),"
            + "(239,'tools','resolution',''),"
            + "(240,'tools','resolution',''),"
            + "(241,'tools','resolution',''),"
            + "(242,'tools','resolution',''),"
            + "(243,'tools','resolution',''),"
            + "(244,'tools','resolution',''),"
            + "(245,'tools','resolution',''),"
            + "(246,'tools','resolution',''),"
            + "(247,'tools','resolution',''),"
            + "(248,'tools','resolution',''),"
            + "(249,'tools','resolution',''),"
            + "(251,'tools','resolution',''),"
            + "(252,'tools','resolution',''),"
            + "(253,'tools','resolution',''),"
            + "(254,'tools','resolution',''),"
            + "(255,'tools','resolution',''),"
            + "(256,'tools','resolution',''),"
            + "(257,'tools','resolution',''),"
            + "(258,'tools','resolution',''),"
            + "(259,'tools','resolution',''),"
            + "(260,'tools','resolution',''),"
            + "(261,'tools','resolution',''),"
            + "(262,'tools','resolution',''),"
            + "(263,'tools','resolution',''),"
            + "(264,'tools','resolution',''),"
            + "(265,'tools','resolution','11 megapixels'),"
            + "(266,'tools','resolution',''),"
            + "(267,'tools','resolution','16.7 megapixel'),"
            + "(268,'tools','resolution',''),"
            + "(269,'tools','resolution',''),"
            + "(270,'tools','resolution',''),"
            + "(271,'tools','resolution',''),"
            + "(272,'tools','resolution','6.3 megapixel'),"
            + "(273,'tools','resolution',''),"
            + "(274,'tools','resolution',''),"
            + "(275,'tools','resolution',''),"
            + "(276,'tools','resolution',''),"
            + "(277,'tools','resolution',''),"
            + "(278,'tools','resolution',''),"
            + "(279,'tools','resolution',''),"
            + "(280,'tools','resolution',''),"
            + "(281,'tools','resolution',''),"
            + "(282,'tools','resolution',''),"
            + "(285,'tools','resolution',''),"
            + "(286,'tools','resolution',''),"
            + "(287,'tools','resolution',''),"
            + "(288,'tools','resolution',''),"
            + "(290,'tools','resolution','8 megapixel'),"
            + "(291,'tools','resolution',''),"
            + "(293,'tools','resolution',''),"
            + "(295,'tools','resolution','300 dpi'),"
            + "(296,'tools','resolution',''),"
            + "(297,'tools','resolution',''),"
            + "(298,'tools','resolution',''),"
            + "(300,'tools','resolution',''),"
            + "(301,'tools','resolution',''),"
            + "(302,'tools','resolution',''),"
            + "(303,'tools','resolution',''),"
            + "(304,'tools','resolution',''),"
            + "(305,'tools','resolution',''),"
            + "(306,'tools','resolution',''),"
            + "(307,'tools','resolution',''),"
            + "(308,'tools','resolution',''),"
            + "(309,'tools','resolution',''),"
            + "(310,'tools','resolution',''),"
            + "(311,'tools','resolution',''),"
            + "(312,'tools','resolution',''),"
            + "(313,'tools','resolution',''),"
            + "(314,'tools','resolution',''),"
            + "(315,'tools','resolution',''),"
            + "(316,'tools','resolution',''),"
            + "(317,'tools','resolution',''),"
            + "(318,'tools','resolution',''),"
            + "(319,'tools','resolution',''),"
            + "(320,'tools','resolution',''),"
            + "(321,'tools','resolution',''),"
            + "(322,'tools','resolution',''),"
            + "(323,'tools','resolution','33 megapixel'),"
            + "(324,'tools','resolution',''),"
            + "(325,'tools','resolution',''),"
            + "(326,'tools','resolution',''),"
            + "(327,'tools','resolution',''),"
            + "(328,'tools','resolution',''),"
            + "(329,'tools','resolution','400ppi'),"
            + "(330,'tools','resolution','10 megapixel'),"
            + "(331,'tools','resolution',''),"
            + "(332,'tools','resolution','10'),"
            + "(334,'tools','resolution',''),"
            + "(335,'tools','resolution',''),"
            + "(336,'tools','resolution',''),"
            + "(337,'tools','resolution',''),"
            + "(338,'tools','resolution',''),"
            + "(339,'tools','resolution',''),"
            + "(340,'tools','resolution',''),"
            + "(341,'tools','resolution',''),"
            + "(342,'tools','resolution',''),"
            + "(343,'tools','resolution',''),"
            + "(344,'tools','resolution',''),"
            + "(346,'tools','resolution',''),"
            + "(347,'tools','resolution',''),"
            + "(349,'tools','resolution',''),"
            + "(350,'tools','resolution',''),"
            + "(351,'tools','resolution',''),"
            + "(352,'tools','resolution',''),"
            + "(353,'tools','resolution',''),"
            + "(354,'tools','resolution',''),"
            + "(355,'tools','resolution',''),"
            + "(356,'tools','resolution',''),"
            + "(357,'tools','resolution',''),"
            + "(358,'tools','resolution',''),"
            + "(359,'tools','resolution',''),"
            + "(360,'tools','resolution',''),"
            + "(361,'tools','resolution',''),"
            + "(362,'tools','resolution',''),"
            + "(363,'tools','resolution',''),"
            + "(364,'tools','resolution',''),"
            + "(365,'tools','resolution',''),"
            + "(366,'tools','resolution',''),"
            + "(367,'tools','resolution',''),"
            + "(368,'tools','resolution',''),"
            + "(369,'tools','resolution',''),"
            + "(370,'tools','resolution',''),"
            + "(371,'tools','resolution',''),"
            + "(372,'tools','resolution',''),"
            + "(373,'tools','resolution',''),"
            + "(374,'tools','resolution',''),"
            + "(377,'tools','resolution','65 megapixels'),"
            + "(378,'tools','resolution',''),"
            + "(380,'tools','resolution',''),"
            + "(381,'tools','resolution',''),"
            + "(382,'tools','resolution',''),"
            + "(383,'tools','resolution',''),"
            + "(384,'tools','resolution',''),"
            + "(385,'tools','resolution',''),"
            + "(386,'tools','resolution',''),"
            + "(387,'tools','resolution',''),"
            + "(388,'tools','resolution','300ppi'),"
            + "(390,'tools','resolution',''),"
            + "(391,'tools','resolution',''),"
            + "(392,'tools','resolution',''),"
            + "(393,'tools','resolution',''),"
            + "(394,'tools','resolution',''),"
            + "(395,'tools','resolution',''),"
            + "(396,'tools','resolution',''),"
            + "(397,'tools','resolution',''),"
            + "(398,'tools','resolution',''),"
            + "(400,'tools','resolution',''),"
            + "(401,'tools','resolution',''),"
            + "(402,'tools','resolution',''),"
            + "(404,'tools','resolution','48 megapixel'),"
            + "(405,'tools','resolution','16 megapixel'),"
            + "(406,'tools','resolution',''),"
            + "(408,'tools','resolution','16 megapixels'),"
            + "(412,'tools','resolution',''),"
            + "(413,'tools','resolution',''),"
            + "(414,'tools','resolution',''),"
            + "(415,'tools','resolution',''),"
            + "(417,'tools','resolution',''),"
            + "(418,'tools','resolution',''),"
            + "(422,'tools','resolution',''),"
            + "(424,'tools','resolution','400 ppi'),"
            + "(425,'tools','resolution','18.1'),"
            + "(428,'tools','resolution',''),"
            + "(429,'tools','resolution',''),"
            + "(430,'tools','resolution',''),"
            + "(431,'tools','resolution',''),"
            + "(432,'tools','resolution','12 to 192 megapixels'),"
            + "(433,'tools','resolution',''),"
            + "(436,'tools','resolution',''),"
            + "(437,'tools','resolution',''),"
            + "(438,'tools','resolution',''),"
            + "(439,'tools','resolution',''),"
            + "(440,'tools','resolution',''),"
            + "(441,'tools','resolution',''),"
            + "(442,'tools','resolution',''),"
            + "(443,'tools','resolution',''),"
            + "(444,'tools','resolution',''),"
            + "(445,'tools','resolution',''),"
            + "(446,'tools','resolution','')"
            )
    void seedToolsLookupsResolutionAttribute();
    
    /*
     * tools serial number attributes definitions
     */
    @SqlUpdate(
            "INSERT INTO lookups(id, name, attribute, value) VALUES"
            + "(1,'tools','serialNumber',' R04/19825 and N04/83 of file NLA/15811 relate.'),"
            + "(2,'tools','serialNumber',''),"
            + "(3,'tools','serialNumber',''),"
            + "(4,'tools','serialNumber',''),"
            + "(5,'tools','serialNumber',''),"
            + "(6,'tools','serialNumber',''),"
            + "(7,'tools','serialNumber',''),"
            + "(8,'tools','serialNumber',''),"
            + "(9,'tools','serialNumber',''),"
            + "(10,'tools','serialNumber',''),"
            + "(11,'tools','serialNumber',''),"
            + "(12,'tools','serialNumber',''),"
            + "(13,'tools','serialNumber',''),"
            + "(14,'tools','serialNumber',''),"
            + "(15,'tools','serialNumber',''),"
            + "(21,'tools','serialNumber',''),"
            + "(22,'tools','serialNumber',''),"
            + "(23,'tools','serialNumber',''),"
            + "(41,'tools','serialNumber',''),"
            + "(61,'tools','serialNumber',''),"
            + "(81,'tools','serialNumber',''),"
            + "(82,'tools','serialNumber',''),"
            + "(101,'tools','serialNumber',''),"
            + "(102,'tools','serialNumber',''),"
            + "(121,'tools','serialNumber',''),"
            + "(141,'tools','serialNumber',''),"
            + "(142,'tools','serialNumber',''),"
            + "(143,'tools','serialNumber',''),"
            + "(145,'tools','serialNumber',''),"
            + "(163,'tools','serialNumber',''),"
            + "(183,'tools','serialNumber',''),"
            + "(184,'tools','serialNumber',''),"
            + "(203,'tools','serialNumber',''),"
            + "(204,'tools','serialNumber',''),"
            + "(205,'tools','serialNumber',''),"
            + "(206,'tools','serialNumber','SN1515'),"
            + "(207,'tools','serialNumber','SN1517'),"
            + "(208,'tools','serialNumber',''),"
            + "(212,'tools','serialNumber',''),"
            + "(213,'tools','serialNumber',' images supplied by agent=AIATSIS'),"
            + "(214,'tools','serialNumber',''),"
            + "(215,'tools','serialNumber','SN16535'),"
            + "(216,'tools','serialNumber',''),"
            + "(217,'tools','serialNumber',''),"
            + "(218,'tools','serialNumber',''),"
            + "(219,'tools','serialNumber',''),"
            + "(220,'tools','serialNumber',''),"
            + "(221,'tools','serialNumber',''),"
            + "(222,'tools','serialNumber','SN18107034'),"
            + "(223,'tools','serialNumber',''),"
            + "(224,'tools','serialNumber',''),"
            + "(225,'tools','serialNumber','SN171231'),"
            + "(226,'tools','serialNumber',''),"
            + "(227,'tools','serialNumber',''),"
            + "(228,'tools','serialNumber','SN601175'),"
            + "(229,'tools','serialNumber','SN500290'),"
            + "(230,'tools','serialNumber','SN1141'),"
            + "(231,'tools','serialNumber','SN1305'),"
            + "(232,'tools','serialNumber','SN1859'),"
            + "(233,'tools','serialNumber','SN2382'),"
            + "(234,'tools','serialNumber','SN10058'),"
            + "(235,'tools','serialNumber','SN7800351'),"
            + "(236,'tools','serialNumber','SN7800360'),"
            + "(237,'tools','serialNumber','SN8X00160'),"
            + "(238,'tools','serialNumber','SN0030015'),"
            + "(239,'tools','serialNumber','SN1519'),"
            + "(240,'tools','serialNumber','SN2406'),"
            + "(241,'tools','serialNumber','SN2602'),"
            + "(242,'tools','serialNumber','SN3100313'),"
            + "(243,'tools','serialNumber','SN1516'),"
            + "(244,'tools','serialNumber',''),"
            + "(245,'tools','serialNumber','SN796'),"
            + "(246,'tools','serialNumber','SN240204-005135'),"
            + "(247,'tools','serialNumber',''),"
            + "(248,'tools','serialNumber','SN100259'),"
            + "(249,'tools','serialNumber',''),"
            + "(251,'tools','serialNumber','SN270030'),"
            + "(252,'tools','serialNumber','SN360080'),"
            + "(253,'tools','serialNumber','SN360143'),"
            + "(254,'tools','serialNumber','SN440533'),"
            + "(255,'tools','serialNumber','SN151950'),"
            + "(256,'tools','serialNumber','SN0200311'),"
            + "(257,'tools','serialNumber','SN20216'),"
            + "(258,'tools','serialNumber','SN2586'),"
            + "(259,'tools','serialNumber','SN240204-004042'),"
            + "(260,'tools','serialNumber',''),"
            + "(261,'tools','serialNumber','SN240204-005216'),"
            + "(262,'tools','serialNumber','SNS037167'),"
            + "(263,'tools','serialNumber','SN21217'),"
            + "(264,'tools','serialNumber',''),"
            + "(265,'tools','serialNumber',''),"
            + "(266,'tools','serialNumber',''),"
            + "(267,'tools','serialNumber',''),"
            + "(268,'tools','serialNumber','SC1200741'),"
            + "(269,'tools','serialNumber',''),"
            + "(270,'tools','serialNumber','SN21217'),"
            + "(271,'tools','serialNumber',''),"
            + "(272,'tools','serialNumber',''),"
            + "(273,'tools','serialNumber','SN22193'),"
            + "(274,'tools','serialNumber','SN22195'),"
            + "(275,'tools','serialNumber','SN22196'),"
            + "(276,'tools','serialNumber','SN22213'),"
            + "(277,'tools','serialNumber',''),"
            + "(278,'tools','serialNumber',''),"
            + "(279,'tools','serialNumber',''),"
            + "(280,'tools','serialNumber',''),"
            + "(281,'tools','serialNumber',''),"
            + "(282,'tools','serialNumber','SN470405272023'),"
            + "(285,'tools','serialNumber','SN470505319001'),"
            + "(286,'tools','serialNumber','SN470505314005'),"
            + "(287,'tools','serialNumber',''),"
            + "(288,'tools','serialNumber',''),"
            + "(290,'tools','serialNumber',''),"
            + "(291,'tools','serialNumber',''),"
            + "(293,'tools','serialNumber',''),"
            + "(295,'tools','serialNumber','BookPro 7000 Scanner'),"
            + "(296,'tools','serialNumber',''),"
            + "(297,'tools','serialNumber','Verson 3.2'),"
            + "(298,'tools','serialNumber','SN3600056'),"
            + "(300,'tools','serialNumber','SN470505355000'),"
            + "(301,'tools','serialNumber','SN470505356005'),"
            + "(302,'tools','serialNumber','SN470606010002'),"
            + "(303,'tools','serialNumber','SN470606011002'),"
            + "(304,'tools','serialNumber','SN470606013005'),"
            + "(305,'tools','serialNumber','SN22624'),"
            + "(306,'tools','serialNumber',''),"
            + "(307,'tools','serialNumber',''),"
            + "(308,'tools','serialNumber',''),"
            + "(309,'tools','serialNumber',''),"
            + "(310,'tools','serialNumber','SN240204-006030'),"
            + "(311,'tools','serialNumber','SN3280'),"
            + "(312,'tools','serialNumber',''),"
            + "(313,'tools','serialNumber','SN470606212000'),"
            + "(314,'tools','serialNumber','SN470606212003'),"
            + "(315,'tools','serialNumber','SN470606212004'),"
            + "(316,'tools','serialNumber','SN470606279003'),"
            + "(317,'tools','serialNumber','SN470606282001'),"
            + "(318,'tools','serialNumber','SN470606284005'),"
            + "(319,'tools','serialNumber','SN9Y00263'),"
            + "(320,'tools','serialNumber',''),"
            + "(321,'tools','serialNumber','SN470606163004'),"
            + "(322,'tools','serialNumber','SN470606163004'),"
            + "(323,'tools','serialNumber',''),"
            + "(324,'tools','serialNumber','SNAX24-00064'),"
            + "(325,'tools','serialNumber','SNAX24-00066'),"
            + "(326,'tools','serialNumber',''),"
            + "(327,'tools','serialNumber','SNAX24-00067'),"
            + "(328,'tools','serialNumber','SNAX24-00068'),"
            + "(329,'tools','serialNumber',''),"
            + "(330,'tools','serialNumber',''),"
            + "(331,'tools','serialNumber','SN139'),"
            + "(332,'tools','serialNumber','600 pixels @ highest resolution'),"
            + "(334,'tools','serialNumber','SN470907164010'),"
            + "(335,'tools','serialNumber','SN471007257005'),"
            + "(336,'tools','serialNumber','SN471007257004'),"
            + "(337,'tools','serialNumber','SN471007257007'),"
            + "(338,'tools','serialNumber','SN471007257003'),"
            + "(339,'tools','serialNumber',''),"
            + "(340,'tools','serialNumber',''),"
            + "(341,'tools','serialNumber',''),"
            + "(342,'tools','serialNumber',''),"
            + "(343,'tools','serialNumber','SNAX24-00112'),"
            + "(344,'tools','serialNumber',''),"
            + "(346,'tools','serialNumber',''),"
            + "(347,'tools','serialNumber',''),"
            + "(349,'tools','serialNumber','SN270327'),"
            + "(350,'tools','serialNumber','SN4105'),"
            + "(351,'tools','serialNumber','SN00939'),"
            + "(352,'tools','serialNumber','SN1366'),"
            + "(353,'tools','serialNumber',''),"
            + "(354,'tools','serialNumber','SN53958'),"
            + "(355,'tools','serialNumber','SN53891'),"
            + "(356,'tools','serialNumber','SN53016'),"
            + "(357,'tools','serialNumber','SN21999'),"
            + "(358,'tools','serialNumber',''),"
            + "(359,'tools','serialNumber','SN471208261000'),"
            + "(360,'tools','serialNumber','SN471208260007'),"
            + "(361,'tools','serialNumber','SN471208261005'),"
            + "(362,'tools','serialNumber','SN471208261004'),"
            + "(363,'tools','serialNumber','SN471208260006'),"
            + "(364,'tools','serialNumber','SN70264'),"
            + "(365,'tools','serialNumber','SN0200311'),"
            + "(366,'tools','serialNumber',''),"
            + "(367,'tools','serialNumber',''),"
            + "(368,'tools','serialNumber',''),"
            + "(369,'tools','serialNumber',''),"
            + "(370,'tools','serialNumber',''SN P5610500127'),"
            + "(371,'tools','serialNumber',''SN P5610500121'),"
            + "(372,'tools','serialNumber',''SN P5610500124'),"
            + "(373,'tools','serialNumber',''SN P5631100073'),"
            + "(374,'tools','serialNumber',''),"
            + "(377,'tools','serialNumber',''),"
            + "(378,'tools','serialNumber',''),"
            + "(380,'tools','serialNumber',''),"
            + "(381,'tools','serialNumber',''),"
            + "(382,'tools','serialNumber',''),"
            + "(383,'tools','serialNumber',''),"
            + "(384,'tools','serialNumber','SN3600082'),"
            + "(385,'tools','serialNumber','SN40450'),"
            + "(386,'tools','serialNumber','SN520511'),"
            + "(387,'tools','serialNumber',''),"
            + "(388,'tools','serialNumber',''),"
            + "(390,'tools','serialNumber','SN471410123000'),"
            + "(391,'tools','serialNumber','SN471410123001'),"
            + "(392,'tools','serialNumber','SN471410123010'),"
            + "(393,'tools','serialNumber','SN471610152005'),"
            + "(394,'tools','serialNumber','SN461609265011'),"
            + "(395,'tools','serialNumber','SN0520515'),"
            + "(396,'tools','serialNumber','SN471610207007'),"
            + "(397,'tools','serialNumber',''),"
            + "(398,'tools','serialNumber','SN9600035'),"
            + "(400,'tools','serialNumber',''),"
            + "(401,'tools','serialNumber',''),"
            + "(402,'tools','serialNumber',''),"
            + "(404,'tools','serialNumber','29.1069'),"
            + "(405,'tools','serialNumber',''),"
            + "(406,'tools','serialNumber',''),"
            + "(408,'tools','serialNumber',''),"
            + "(412,'tools','serialNumber','SN471610207003'),"
            + "(413,'tools','serialNumber','SN471610207006'),"
            + "(414,'tools','serialNumber','SN471610207005'),"
            + "(415,'tools','serialNumber',''),"
            + "(417,'tools','serialNumber','SNAX24-00067'),"
            + "(418,'tools','serialNumber','SNAX24-00068'),"
            + "(422,'tools','serialNumber',''),"
            + "(424,'tools','serialNumber','2040020'),"
            + "(425,'tools','serialNumber',''),"
            + "(428,'tools','serialNumber','SN51050'),"
            + "(429,'tools','serialNumber','SN1286'),"
            + "(430,'tools','serialNumber','SN8300295'),"
            + "(431,'tools','serialNumber',''),"
            + "(432,'tools','serialNumber','37.1029'),"
            + "(433,'tools','serialNumber','SN1352'),"
            + "(436,'tools','serialNumber','DP41036022'),"
            + "(437,'tools','serialNumber',''),"
            + "(438,'tools','serialNumber','SN240629'),"
            + "(439,'tools','serialNumber',''),"
            + "(440,'tools','serialNumber',''),"
            + "(441,'tools','serialNumber',''),"
            + "(442,'tools','serialNumber',''),"
            + "(443,'tools','serialNumber',''),"
            + "(444,'tools','serialNumber',''),"
            + "(445,'tools','serialNumber',''),"
            + "(446,'tools','serialNumber','')")
            void seedToolsLookupsSerialAttribute();
 
    /*
     * tools notes attribute definitions
     */
    @SqlUpdate(
            "INSERT INTO lookups(id, name, attribute, value) VALUES"
            + "(1,'tools','notes','Used MagicScan software for image capture. NLA  asset 26105 written off and disposed of in 2003/4 FY due to breakdown. TRIM folios R04/14022'),"
            + "(2,'tools','notes',''),"
            + "(3,'tools','notes',''),"
            + "(4,'tools','notes',''),"
            + "(5,'tools','notes',''),"
            + "(6,'tools','notes',''),"
            + "(7,'tools','notes',''),"
            + "(8,'tools','notes',''),"
            + "(9,'tools','notes',''),"
            + "(10,'tools','notes',''),"
            + "(11,'tools','notes',''),"
            + "(12,'tools','notes',''),"
            + "(13,'tools','notes',''),"
            + "(14,'tools','notes',''),"
            + "(15,'tools','notes',''),"
            + "(21,'tools','notes','Reflective and transmissive scanner with ScanWizard Pro software for image capture'),"
            + "(22,'tools','notes','Transmissive scanner with Nikon Scan 4.0 software for image capture'),"
            + "(23,'tools','notes',''),"
            + "(41,'tools','notes',''),"
            + "(61,'tools','notes','Used for Photo CD conversion'),"
            + "(81,'tools','notes',''),"
            + "(82,'tools','notes',''),"
            + "(101,'tools','notes',''),"
            + "(102,'tools','notes',''),"
            + "(121,'tools','notes','Uses Scanflo software for image capture'),"
            + "(141,'tools','notes',''),"
            + "(142,'tools','notes',''),"
            + "(143,'tools','notes','Reflective and transmissive scanner with Silverfast software for image capture'),"
            + "(145,'tools','notes','Transmissive scanner with Silverfast image capture software'),"
            + "(163,'tools','notes','Used to produce images in Job 12429 - Film used was Kodak T400 CN '),"
            + "(183,'tools','notes','For digital born images acquired by the Library'),"
            + "(184,'tools','notes','For born digital images acquired by the Library'),"
            + "(203,'tools','notes',''),"
            + "(204,'tools','notes',''),"
            + "(205,'tools','notes',''),"
            + "(206,'tools','notes',''),"
            + "(207,'tools','notes',''),"
            + "(208,'tools','notes',''),"
            + "(212,'tools','notes',''),"
            + "(213,'tools','notes','March 2005+'),"
            + "(214,'tools','notes','Scanning software for AIATSIS' Imageware Bookeye Scanner'),"
            + "(215,'tools','notes',''),"
            + "(216,'tools','notes',''),"
            + "(217,'tools','notes',''),"
            + "(218,'tools','notes',''),"
            + "(219,'tools','notes',''),"
            + "(220,'tools','notes',''),"
            + "(221,'tools','notes',''),"
            + "(222,'tools','notes',''),"
            + "(223,'tools','notes',''),"
            + "(224,'tools','notes',''),"
            + "(225,'tools','notes',''),"
            + "(226,'tools','notes',''),"
            + "(227,'tools','notes',''),"
            + "(228,'tools','notes',''),"
            + "(229,'tools','notes',''),"
            + "(230,'tools','notes',''),"
            + "(231,'tools','notes',''),"
            + "(232,'tools','notes',''),"
            + "(233,'tools','notes',''),"
            + "(234,'tools','notes',''),"
            + "(235,'tools','notes',''),"
            + "(236,'tools','notes',''),"
            + "(237,'tools','notes',''),"
            + "(238,'tools','notes',''),"
            + "(239,'tools','notes',''),"
            + "(240,'tools','notes',''),"
            + "(241,'tools','notes',''),"
            + "(242,'tools','notes',''),"
            + "(243,'tools','notes',''),"
            + "(244,'tools','notes',''),"
            + "(245,'tools','notes','Q-audio replay machine'),"
            + "(246,'tools','notes','Q-audio A/D converter'),"
            + "(247,'tools','notes','Q-audio sound card'),"
            + "(248,'tools','notes','Q-audio replay machine'),"
            + "(249,'tools','notes',''),"
            + "(251,'tools','notes','Crystal Mastering replay machine'),"
            + "(252,'tools','notes','Crystal Mastering replay machine'),"
            + "(253,'tools','notes','Crystal Mastering replay machine'),"
            + "(254,'tools','notes','Crystal Mastering replay machine'),"
            + "(255,'tools','notes','Crystal Mastering replay machine'),"
            + "(256,'tools','notes','Crystal Mastering replay machine'),"
            + "(257,'tools','notes','Crystal Mastering replay machine'),"
            + "(258,'tools','notes','Crystal Mastering A/D converter'),"
            + "(259,'tools','notes','Crystal Mastering A/D converter'),"
            + "(260,'tools','notes','Crystal Mastering sound card'),"
            + "(261,'tools','notes','Qaudio A/D converter'),"
            + "(262,'tools','notes','Qaudio replay machine'),"
            + "(263,'tools','notes','Qaudio replay machine'),"
            + "(264,'tools','notes','As used by Public Programs'),"
            + "(265,'tools','notes',''),"
            + "(266,'tools','notes','Camera owned and used by Document Supply Service staff'),"
            + "(267,'tools','notes',''),"
            + "(268,'tools','notes','Transmissive and reflective scanner'),"
            + "(269,'tools','notes','Capture software for CREO iQsmart2'),"
            + "(270,'tools','notes','QAudio replay machine'),"
            + "(271,'tools','notes','QAudio sound card'),"
            + "(272,'tools','notes',''),"
            + "(273,'tools','notes','Asset no. 27518'),"
            + "(274,'tools','notes','Asset no. 27515'),"
            + "(275,'tools','notes','Asset no. 25516'),"
            + "(276,'tools','notes','Asset no. 25517'),"
            + "(277,'tools','notes','Unknown refers to signal sources that are not under the control of SPATS'),"
            + "(278,'tools','notes','Apogee Mini-Me A/D Converter contains internal sound card. '),"
            + "(279,'tools','notes','Nagra V recorder and A/D converter contains internal sound card.'),"
            + "(280,'tools','notes','Collection Preservation Section digital camera'),"
            + "(281,'tools','notes','Collection Preservation Section digital camera'),"
            + "(282,'tools','notes',''),"
            + "(285,'tools','notes',''),"
            + "(286,'tools','notes',''),"
            + "(287,'tools','notes',''),"
            + "(288,'tools','notes',''),"
            + "(290,'tools','notes','On loan while 1Ds MkII is being repaired'),"
            + "(291,'tools','notes',''),"
            + "(293,'tools','notes',''),"
            + "(295,'tools','notes','Overhead Scanner used by Document Supply Service'),"
            + "(296,'tools','notes',''),"
            + "(297,'tools','notes',''),"
            + "(298,'tools','notes',''),"
            + "(300,'tools','notes',''),"
            + "(301,'tools','notes',''),"
            + "(302,'tools','notes',''),"
            + "(303,'tools','notes',''),"
            + "(304,'tools','notes',''),"
            + "(305,'tools','notes',''),"
            + "(306,'tools','notes',''),"
            + "(307,'tools','notes',''),"
            + "(308,'tools','notes',''),"
            + "(309,'tools','notes',''),"
            + "(310,'tools','notes',''),"
            + "(311,'tools','notes',''),"
            + "(312,'tools','notes','Transmissive and reflective scanner'),"
            + "(313,'tools','notes','Asset no. 27705'),"
            + "(314,'tools','notes','Asset no. 27706 '),"
            + "(315,'tools','notes','Asset no. 27707'),"
            + "(316,'tools','notes','Asset no. 27731'),"
            + "(317,'tools','notes','Asset no. 27732'),"
            + "(318,'tools','notes','Asset no. 27733'),"
            + "(319,'tools','notes',''),"
            + "(320,'tools','notes',''),"
            + "(321,'tools','notes',''),"
            + "(322,'tools','notes',''),"
            + "(323,'tools','notes',''),"
            + "(324,'tools','notes',''),"
            + "(325,'tools','notes',''),"
            + "(326,'tools','notes',''),"
            + "(327,'tools','notes',''),"
            + "(328,'tools','notes',''),"
            + "(329,'tools','notes','Located in Maps'),"
            + "(330,'tools','notes',''),"
            + "(331,'tools','notes',''),"
            + "(332,'tools','notes','200 x 13'),"
            + "(334,'tools','notes','Asset no. 27886'),"
            + "(335,'tools','notes','Asset no. 27920'),"
            + "(336,'tools','notes','Asset no. 27921'),"
            + "(337,'tools','notes','Asset no. 27922'),"
            + "(338,'tools','notes','Asset no. 27923'),"
            + "(339,'tools','notes',''),"
            + "(340,'tools','notes','initial version -10.0.1'),"
            + "(341,'tools','notes','Note there is no serial number listed for this tool. It is to be used when a non-NLA machine is used.'),"
            + "(342,'tools','notes',''),"
            + "(343,'tools','notes','Asset number 28193'),"
            + "(344,'tools','notes',''),"
            + "(346,'tools','notes','Audio processing software used for derivatives'),"
            + "(347,'tools','notes',''),"
            + "(349,'tools','notes',''),"
            + "(350,'tools','notes','Crystal Mastering'),"
            + "(351,'tools','notes','Crystal Mastering'),"
            + "(352,'tools','notes',''),"
            + "(353,'tools','notes',''),"
            + "(354,'tools','notes','Asset number: 27155'),"
            + "(355,'tools','notes','Asset number: 27154'),"
            + "(356,'tools','notes','Asset number: 26085'),"
            + "(357,'tools','notes','Asset number: 25757'),"
            + "(358,'tools','notes','Asset no. 27930'),"
            + "(359,'tools','notes','Asset no. 28213'),"
            + "(360,'tools','notes','Asset no. 28217'),"
            + "(361,'tools','notes','Asset no. 28215'),"
            + "(362,'tools','notes','Asset no. 28214'),"
            + "(363,'tools','notes','Asset no. 28216'),"
            + "(364,'tools','notes',''),"
            + "(365,'tools','notes',''),"
            + "(366,'tools','notes','For use when DAT is ingested outside of the DAT Module system.'),"
            + "(367,'tools','notes','For use when DAT is ingested outside of DAT Module system.'),"
            + "(368,'tools','notes',''),"
            + "(369,'tools','notes',''),"
            + "(370,'tools','notes','Used in Document Supply'),"
            + "(371,'tools','notes','Used in Document Supply'),"
            + "(372,'tools','notes','Used by Document Supply'),"
            + "(373,'tools','notes','Used in Document Supply'),"
            + "(374,'tools','notes',''),"
            + "(377,'tools','notes',''),"
            + "(378,'tools','notes',''),"
            + "(380,'tools','notes',''),"
            + "(381,'tools','notes',''),"
            + "(382,'tools','notes',''),"
            + "(383,'tools','notes',''),"
            + "(384,'tools','notes',''),"
            + "(385,'tools','notes','Crystal Mastering Tascam 122 MkIII'),"
            + "(386,'tools','notes','Crystal Mastering machine'),"
            + "(387,'tools','notes',''),"
            + "(388,'tools','notes',''),"
            + "(390,'tools','notes','Asset no. 28549'),"
            + "(391,'tools','notes','Asset no. 28550'),"
            + "(392,'tools','notes','Asset no. 28551'),"
            + "(393,'tools','notes','Asset no. 28563'),"
            + "(394,'tools','notes','Asset no. 28536'),"
            + "(395,'tools','notes','Microcassette player owned by Bearcage Productions'),"
            + "(396,'tools','notes','Asset no. 28637'),"
            + "(397,'tools','notes',''),"
            + "(398,'tools','notes','US machine converted to 240V/50Hz April 2011.'),"
            + "(400,'tools','notes',''),"
            + "(401,'tools','notes',''),"
            + "(402,'tools','notes','Test for creation of xml file for multiple ingest system'),"
            + "(404,'tools','notes',''),"
            + "(405,'tools','notes',''),"
            + "(406,'tools','notes',''),"
            + "(408,'tools','notes',''),"
            + "(412,'tools','notes','Asset no. 28634'),"
            + "(413,'tools','notes','Asset no. 28636'),"
            + "(414,'tools','notes','Asset no. 28635'),"
            + "(415,'tools','notes',''),"
            + "(417,'tools','notes','DAD synchronised to master clock - Preservation'),"
            + "(418,'tools','notes','DAD synchronised to master clock - Live'),"
            + "(422,'tools','notes',''),"
            + "(424,'tools','notes','Scanner located in Document Supply area'),"
            + "(425,'tools','notes',''),"
            + "(428,'tools','notes',''),"
            + "(429,'tools','notes',''),"
            + "(430,'tools','notes','Crystal Mastering replay machine'),"
            + "(431,'tools','notes','Overhead camera owned by National Centre of Biography'),"
            + "(432,'tools','notes',''),"
            + "(433,'tools','notes',''),"
            + "(436,'tools','notes',''),"
            + "(437,'tools','notes',''),"
            + "(438,'tools','notes',''),"
            + "(439,'tools','notes',''),"
            + "(440,'tools','notes',''),"
            + "(441,'tools','notes',''),"
            + "(442,'tools','notes',''),"
            + "(443,'tools','notes',''),"
            + "(444,'tools','notes',''),"
            + "(445,'tools','notes',''),"
            + "(446,'tools','notes','')"
            )
    void seedToolsLookupsNotesAttribute();

    
    /*
     * Main table indexes - these require review as they might need indexes.
     */
    @SqlUpdate(
            "CREATE UNIQUE INDEX unique_vert "
            + "ON vertex(id, txn_start)")
    void createVertexIndex();

    
    @SqlUpdate(
            "CREATE UNIQUE INDEX unique_edge "
            + "ON edge(id, txn_start)")
    void createEdgeIndex();

    
    @SqlUpdate(
            "CREATE UNIQUE INDEX unique_prop "
            + "ON property(id, txn_start, name)")
    void createPropertyIndex();

    
    @SqlUpdate(
            "CREATE INDEX edge_in_idx "
            + "ON edge(v_in)")
    void createEdgeInVertexIndex();

    
    @SqlUpdate(
            "CREATE INDEX edge_out_idx "
            + "ON edge(v_out)")
    void createEdgeOutVertexIndex();

    
    @SqlQuery(
            "SELECT (COUNT(table_name) = 8) "
            + "FROM information_schema.tables " 
            + "WHERE table_name IN ("
            + "  'VERTEX', 'EDGE', 'PROPERTY', "
            + "  'SESS_VERTEX', 'SESS_EDGE', 'SESS_PROPERTY', "
            + "  'ID_GENERATOR', 'TRANSACTION')")
    boolean schemaTablesExist();
    
    
    @SqlUpdate(
            "DROP TABLE IF EXISTS "
            + "vertex, edge, property, "
            + "sess_vertex, sess_edge, sess_property, "
            + "transaction, id_generator")
    void dropTables();

    
    /*
     * id generation operations
     */
    @GetGeneratedKeys
    @SqlUpdate("INSERT INTO id_generator () "
            + "VALUES ()")
    long newId();

    
    @SqlUpdate("DELETE "
            + "FROM id_generator "
            + "WHERE id < :id")
    void garbageCollectIds(
            @Bind("id") long id);

    
    /*
     * suspend/resume operations
     */
    @SqlBatch("INSERT INTO sess_edge (s_id, id, txn_start, txn_end, v_out, v_in, label, edge_order, state) "
            + "VALUES (:sessId, :id, :txnStart, :txnEnd, :outId, :inId, :label, :edgeOrder, :state)")
    void suspendEdges(
            @Bind("sessId")    Long          sessId,
            @Bind("id")        List<Long>    id,
            @Bind("txnStart")  List<Long>    txnStart,
            @Bind("txnEnd")    List<Long>    txnEnd,
            @Bind("outId")     List<Long>    outId,
            @Bind("inId")      List<Long>    inId,
            @Bind("label")     List<String>  label,
            @Bind("edgeOrder") List<Integer> edgeOrder,
            @Bind("state")     List<String>  state);

    
    @SqlBatch("INSERT INTO sess_vertex (s_id, id, txn_start, txn_end, state) "
            + "VALUES (:sessId, :id, :txnStart, :txnEnd, :state)")
    void suspendVertices(
            @Bind("sessId")    Long         sessId,
            @Bind("id")        List<Long>   id,
            @Bind("txnStart")  List<Long>   txnStart,
            @Bind("txnEnd")    List<Long>   txnEnd,
            @Bind("state")     List<String> state);

    
    @SqlBatch("INSERT INTO sess_property (s_id, id, name, type, value) "
            + "VALUES (:sessId, :id, :name, :type, :value)")
    void suspendProperties(
            @Bind("sessId")    Long         sessId,
            @Bind("id")        List<Long>   id,
            @Bind("name")      List<String> name,
            @Bind("type")      List<String> type,
            @Bind("value")     List<byte[]> value);

    
    @SqlQuery("SELECT id, name, type, value "
            + "FROM sess_property "
            + "WHERE s_id = :sessId")
    @Mapper(PropertyMapper.class)
    List<AmberProperty> resumeProperties(@Bind("sessId") Long sessId);
    
    
    /* Note: resume edge and vertex implemented in AmberGraph
    
    
    /*
     * commit operations
     */
    @SqlUpdate(
            "INSERT INTO transaction (id, time, user, operation)" +
            "VALUES (:id, :time, :user, :operation)")
    void insertTransaction(
            @Bind("id") long id, 
            @Bind("time") long time, 
            @Bind("user") String user,
            @Bind("operation") String operation);

        
    @SqlUpdate("")
    void endElements(
            @Bind("txnId") Long txnId);

    
    @SqlUpdate("SET @txn = :txnId;\n"
            
            // edges            
            + "INSERT INTO edge (id, txn_start, txn_end, v_out, v_in, label, edge_order) "
            + "SELECT id, s_id, 0, v_out, v_in, label, edge_order "
            + "FROM sess_edge "
            + "WHERE s_id = @txn "
            + "AND (state = 'NEW' OR state = 'MOD');\n"

            // vertices            
            + "INSERT INTO vertex (id, txn_start, txn_end) "
            + "SELECT id, s_id, 0 "
            + "FROM sess_vertex "
            + "WHERE s_id = @txn "
            + "AND (state = 'NEW' OR state = 'MOD');\n"

            // properties            
            + "INSERT INTO property (id, txn_start, txn_end, name, type, value) "
            + "SELECT id, s_id, 0, name, type, value "
            + "FROM sess_property "
            + "WHERE s_id = @txn") 
    void startElements(
            @Bind("txnId") Long txnId);


    void close();


    @SqlUpdate("SET @sessId = :sessId;\n" +
    
            "DELETE FROM sess_vertex " +
            "WHERE s_id = @sessId;\n" +
            
            "DELETE FROM sess_edge " +
            "WHERE s_id = @sessId;\n" +
            
            "DELETE FROM sess_property " +
            "WHERE s_id = @sessId;\n")
    void clearSession(
            @Bind("sessId") Long sessId);
    
    
    @CreateSqlObject
    public abstract Lookups lookups();
}

